using ED8Editor.Core;

namespace ED8Editor.Phyre.Authoring;

/// <summary>
/// Every class the game's clusters describe, as data rather than as bytes copied
/// from one of its files.
///
/// A cluster carries the layout of the classes it uses — the size and alignment
/// of each, the offset, size and flags of each member. Those are facts about the
/// engine, not about the file: measured over the 32 796 clusters the game ships,
/// 175 classes and 521 members appear, and <b>no class is ever described two
/// different ways</b>. So one library can serve every cluster, and a model can be
/// written without opening a model.
///
/// The library speaks <b>names</b>, never ids. Inside a cluster a class or a type
/// is an index into that cluster's own tables, so an id means nothing once it
/// leaves the file it came from. The engine resolves those indices in
/// <c>PhyreNamespacePacked.cpp</c>: a member's type id below the type count names
/// a type, at or above it names <c>class[id - typeCount - 1]</c>; a superclass id
/// is one-based over the classes alone, zero meaning none. <see cref="Descriptors"/>
/// applies that rule in reverse.
///
/// Generated by <c>--emit-library</c> and checked back against the game: the
/// namespace this table produces for a shipped cluster has to be, byte for byte,
/// the one that cluster carries.
/// </summary>
public static class PhyreSchemaLibrary
{
    private sealed record MemberRow(
        string Name, string TypeName, uint ValueOffset, uint Size, uint Flags, uint FixedArraySize);

    private sealed record ClassRow(
        string Name,
        string SuperClassName,
        uint Size,
        uint Alignment,
        int OffsetFromParent,
        int OffsetToBase,
        int OffsetToBaseInAllocatedBlock,
        uint Flags,
        uint DefaultBufferOffset,
        MemberRow[] Members);

    private static readonly MemberRow[] NoMembers = Array.Empty<MemberRow>();

    // Generated from 32796 clusters by --emit-library.
    private static readonly string[] PrimitiveTypes =
    {
        "bool",
        "float",
        "PAnimationKeyDataType",
        "PChar",
        "PContextSwitch",
        "PInt16",
        "PInt32",
        "PLightType",
        "PLODBlendType",
        "PLODMetricType",
        "PRenderDataType",
        "PSceneRenderPassType",
        "PShadowCasterType",
        "PTextureFormatBase",
        "PUInt16",
        "PUInt32",
        "PUInt8",
    };

    private static readonly ClassRow[] Rows =
    {
        new("CD3D11_BLEND_DESC", "-", 264, 4, 0, 0, 0, 0x0, 0, new MemberRow[]
        {
            new("AlphaToCoverageEnable", "PInt32", 0, 4, 0x10, 0),
            new("IndependentBlendEnable", "PInt32", 4, 4, 0x10, 0),
            new("RenderTarget", "D3D11_RENDER_TARGET_BLEND_DESC", 8, 32, 0x10, 8),
        }),
        new("CD3D11_DEPTH_STENCIL_DESC", "-", 52, 4, 0, 0, 0, 0x0, 0, new MemberRow[]
        {
            new("DepthEnable", "PInt32", 0, 4, 0x10, 0),
            new("DepthWriteMask", "PInt32", 4, 4, 0x30, 0),
            new("DepthFunc", "PInt32", 8, 4, 0x30, 0),
            new("StencilEnable", "PInt32", 12, 4, 0x10, 0),
            new("StencilReadMask", "PUInt8", 16, 1, 0x10, 0),
            new("StencilWriteMask", "PUInt8", 17, 1, 0x10, 0),
            new("FrontFace", "D3D11_DEPTH_STENCILOP_DESC", 20, 16, 0x10, 0),
            new("BackFace", "D3D11_DEPTH_STENCILOP_DESC", 36, 16, 0x10, 0),
        }),
        new("CD3D11_RASTERIZER_DESC", "-", 40, 4, 0, 0, 0, 0x0, 0, new MemberRow[]
        {
            new("FillMode", "PInt32", 0, 4, 0x30, 0),
            new("CullMode", "PInt32", 4, 4, 0x30, 0),
            new("FrontCounterClockwise", "PInt32", 8, 4, 0x10, 0),
            new("DepthBias", "PInt32", 12, 4, 0x10, 0),
            new("DepthBiasClamp", "float", 16, 4, 0x10, 0),
            new("SlopeScaledDepthBias", "float", 20, 4, 0x10, 0),
            new("DepthClipEnable", "PInt32", 24, 4, 0x10, 0),
            new("ScissorEnable", "PInt32", 28, 4, 0x10, 0),
            new("MultisampleEnable", "PInt32", 32, 4, 0x10, 0),
            new("AntialiasedLineEnable", "PInt32", 36, 4, 0x10, 0),
        }),
        new("D3D11_DEPTH_STENCILOP_DESC", "-", 16, 4, 0, 0, 0, 0x0, 0, new MemberRow[]
        {
            new("StencilFailOp", "PInt32", 0, 4, 0x30, 0),
            new("StencilDepthFailOp", "PInt32", 4, 4, 0x30, 0),
            new("StencilPassOp", "PInt32", 8, 4, 0x30, 0),
            new("StencilFunc", "PInt32", 12, 4, 0x30, 0),
        }),
        new("D3D11_RENDER_TARGET_BLEND_DESC", "-", 32, 4, 0, 0, 0, 0x0, 0, new MemberRow[]
        {
            new("BlendEnable", "PInt32", 0, 4, 0x10, 0),
            new("SrcBlend", "PInt32", 4, 4, 0x30, 0),
            new("DestBlend", "PInt32", 8, 4, 0x30, 0),
            new("BlendOp", "PInt32", 12, 4, 0x30, 0),
            new("SrcBlendAlpha", "PInt32", 16, 4, 0x30, 0),
            new("DestBlendAlpha", "PInt32", 20, 4, 0x30, 0),
            new("BlendOpAlpha", "PInt32", 24, 4, 0x30, 0),
            new("RenderTargetWriteMask", "PUInt8", 28, 1, 0x10, 0),
        }),
        new("Matrix4", "-", 64, 4, 0, 0, 0, 0x0, 0, new MemberRow[]
        {
            new("m_elements", "float", 0, 4, 0x0, 16),
        }),
        new("PAnimationChannel", "PAnimationChannelBase", 52, 4, 0, 0, 0, 0x0, 0, new MemberRow[]
        {
            new("m_times", "PAnimationChannelTimes", 36, 4, 0x12, 0),
            new("m_valueKeys", "PArray<float>", 40, 8, 0x10, 0),
            new("m_keyCount", "PUInt32", 48, 4, 0x10, 0),
        }),
        new("PAnimationChannelBase", "PAnimationChannelTarget", 36, 4, 0, 0, 0, 0x0, 0, new MemberRow[]
        {
            new("m_keyType", "PAnimationKeyDataType", 28, 4, 0x12, 0),
            new("m_interp", "PInt32", 32, 4, 0x30, 0),
        }),
        new("PAnimationChannelTarget", "PBase", 28, 4, 0, 0, 0, 0x0, 0, new MemberRow[]
        {
            new("m_instanceObjectType", "PClassDescriptor", 0, 4, 0x12, 0),
            new("m_instanceObject", "PBase", 4, 4, 0x12, 0),
            new("m_baseObjectType", "PClassDescriptor", 8, 4, 0x12, 0),
            new("m_baseObject", "PBase", 12, 4, 0x12, 0),
            new("m_type", "PInt32", 16, 4, 0x30, 0),
            new("m_name", "PString", 20, 4, 0x10, 0),
            new("m_index", "PUInt32", 24, 4, 0x10, 0),
        }),
        new("PAnimationChannelTimes", "PBase", 12, 4, 0, 0, 0, 0x0, 0, new MemberRow[]
        {
            new("m_timeKeys", "PArray<float>", 4, 8, 0x10, 0),
            new("m_keyCount", "PUInt32", 0, 4, 0x10, 0),
        }),
        new("PAnimationClip", "PBase", 32, 4, 0, 0, 0, 0x0, 0, new MemberRow[]
        {
            new("m_channels", "PArray<PAnimationChannel *>", 4, 8, 0x10, 0),
            new("m_constantChannels", "PArray<PAnimationConstantChannel>", 12, 8, 0x10, 0),
            new("m_constantChannelStartTime", "float", 20, 4, 0x10, 0),
            new("m_constantChannelEndTime", "float", 24, 4, 0x10, 0),
            new("m_binding", "PAnimationClipBinding", 0, 4, 0x12, 0),
            new("m_name", "PString", 28, 4, 0x10, 0),
        }),
        new("PAnimationClipBinding", "PBase", 8, 4, 0, 0, 0, 0x14, 0, new MemberRow[]
        {
            new("m_spuBindingSize", "PUInt16", 0, 2, 0x10, 0),
            new("m_channelCount", "PUInt16", 2, 2, 0x10, 0),
            new("m_constantChannelCount", "PUInt16", 4, 2, 0x10, 0),
            new("m_interpCountLength", "PUInt16", 6, 2, 0x10, 0),
        }),
        new("PAnimationClipBindingChannelMap", "PBase", 4, 2, 0, 0, 0, 0x0, 0, new MemberRow[]
        {
            new("m_destSlotArrayIndex", "PInt16", 0, 2, 0x10, 0),
            new("m_interp", "PUInt16", 2, 2, 0x10, 0),
        }),
        new("PAnimationClipBindingDataBlockCache", "PBase", 16, 4, 0, 0, 0, 0x0, 0, new MemberRow[]
        {
            new("m_sourceChannelIndex", "PUInt16", 12, 2, 0x10, 0),
            new("m_valueWidthAndKeyCount", "PUInt32", 8, 4, 0x10, 0),
        }),
        new("PAnimationConstantChannel", "PAnimationChannelBase", 52, 4, 0, 0, 0, 0x0, 0, new MemberRow[]
        {
            new("m_value", "float", 36, 4, 0x10, 4),
        }),
        new("PAnimationSet", "PBase", 24, 4, 0, 0, 0, 0x0, 0, new MemberRow[]
        {
            new("m_animationClips", "PSharray<PAnimationClip *>", 0, 8, 0x10, 0),
            new("m_targets", "PArray<PAnimationChannelTarget>", 8, 8, 0x10, 0),
            new("m_slotArrayIndices", "PArray<PAnimationSlotListIndex>", 16, 8, 0x10, 0),
        }),
        new("PAnimationSlotListIndex", "PBase", 16, 4, 0, 0, 0, 0x0, 0, new MemberRow[]
        {
            new("m_animKeyType", "PAnimationKeyDataType", 0, 4, 0x12, 0),
            new("m_interp", "PInt32", 4, 4, 0x30, 0),
            new("m_targetIndex", "PUInt32", 8, 4, 0x10, 0),
            new("m_nodeCentricReIndex", "PUInt32", 12, 4, 0x10, 0),
        }),
        new("PArray<float>", "PBase", 8, 4, 0, 0, 0, 0x0, 0, new MemberRow[]
        {
            new("m_count", "PUInt32", 0, 4, 0x0, 0),
            new("m_els", "float", 4, 4, 0x0, 0),
        }),
        new("PArray<PAnimationChannel *>", "PBase", 8, 4, 0, 0, 0, 0x0, 0, new MemberRow[]
        {
            new("m_count", "PUInt32", 0, 4, 0x0, 0),
            new("m_els", "PAnimationChannel", 4, 4, 0x2, 0),
        }),
        new("PArray<PAnimationChannelTarget>", "PBase", 8, 4, 0, 0, 0, 0x0, 0, new MemberRow[]
        {
            new("m_count", "PUInt32", 0, 4, 0x0, 0),
            new("m_els", "PAnimationChannelTarget", 4, 4, 0x0, 0),
        }),
        new("PArray<PAnimationConstantChannel>", "PBase", 8, 4, 0, 0, 0, 0x0, 0, new MemberRow[]
        {
            new("m_count", "PUInt32", 0, 4, 0x0, 0),
            new("m_els", "PAnimationConstantChannel", 4, 4, 0x0, 0),
        }),
        new("PArray<PAnimationSlotListIndex>", "PBase", 8, 4, 0, 0, 0, 0x0, 0, new MemberRow[]
        {
            new("m_count", "PUInt32", 0, 4, 0x0, 0),
            new("m_els", "PAnimationSlotListIndex", 4, 4, 0x0, 0),
        }),
        new("PArray<PContextSwitch *>", "PBase", 8, 4, 0, 0, 0, 0x0, 0, new MemberRow[]
        {
            new("m_count", "PUInt32", 0, 4, 0x0, 0),
            new("m_els", "PContextSwitch", 4, 4, 0x2, 0),
        }),
        new("PArray<PContextVariantFoldingTable>", "PBase", 8, 4, 0, 0, 0, 0x0, 0, new MemberRow[]
        {
            new("m_count", "PUInt32", 0, 4, 0x0, 0),
            new("m_els", "PContextVariantFoldingTable", 4, 4, 0x0, 0),
        }),
        new("PArray<PDataBlockD3D11>", "PBase", 8, 4, 0, 0, 0, 0x0, 0, new MemberRow[]
        {
            new("m_count", "PUInt32", 0, 4, 0x0, 0),
            new("m_els", "PDataBlockD3D11", 4, 4, 0x0, 0),
        }),
        new("PArray<PDynamicSegmentDesc>", "PBase", 8, 4, 0, 0, 0, 0x0, 0, new MemberRow[]
        {
            new("m_count", "PUInt32", 0, 4, 0x0, 0),
            new("m_els", "PDynamicSegmentDesc", 4, 4, 0x0, 0),
        }),
        new("PArray<PEffectVariant *>", "PBase", 8, 4, 0, 0, 0, 0x0, 0, new MemberRow[]
        {
            new("m_count", "PUInt32", 0, 4, 0x0, 0),
            new("m_els", "PEffectVariant", 4, 4, 0x2, 0),
        }),
        new("PArray<PInt32>", "PBase", 8, 4, 0, 0, 0, 0x0, 0, new MemberRow[]
        {
            new("m_count", "PUInt32", 0, 4, 0x0, 0),
            new("m_els", "PInt32", 4, 4, 0x0, 0),
        }),
        new("PArray<PLightType *>", "PBase", 8, 4, 0, 0, 0, 0x0, 0, new MemberRow[]
        {
            new("m_count", "PUInt32", 0, 4, 0x0, 0),
            new("m_els", "PLightType", 4, 4, 0x2, 0),
        }),
        new("PArray<PLODLevel>", "PBase", 8, 4, 0, 0, 0, 0x0, 0, new MemberRow[]
        {
            new("m_count", "PUInt32", 0, 4, 0x0, 0),
            new("m_els", "PLODLevel", 4, 4, 0x0, 0),
        }),
        new("PArray<PMaterialSwitch>", "PBase", 8, 4, 0, 0, 0, 0x0, 0, new MemberRow[]
        {
            new("m_count", "PUInt32", 0, 4, 0x0, 0),
            new("m_els", "PMaterialSwitch", 4, 4, 0x0, 0),
        }),
        new("PArray<PMatrix4>", "PBase", 8, 4, 0, 0, 0, 0x0, 0, new MemberRow[]
        {
            new("m_count", "PUInt32", 0, 4, 0x0, 0),
            new("m_els", "PMatrix4", 4, 4, 0x0, 0),
        }),
        new("PArray<PMeshInstanceSegmentContext>", "PBase", 8, 4, 0, 0, 0, 0x0, 0, new MemberRow[]
        {
            new("m_count", "PUInt32", 0, 4, 0x0, 0),
            new("m_els", "PMeshInstanceSegmentContext", 4, 4, 0x0, 0),
        }),
        new("PArray<PMeshSegment>", "PBase", 8, 4, 0, 0, 0, 0x0, 0, new MemberRow[]
        {
            new("m_count", "PUInt32", 0, 4, 0x0, 0),
            new("m_els", "PMeshSegment", 4, 4, 0x0, 0),
        }),
        new("PArray<PNodeContext>", "PBase", 8, 4, 0, 0, 0, 0x0, 0, new MemberRow[]
        {
            new("m_count", "PUInt32", 0, 4, 0x0, 0),
            new("m_els", "PNodeContext", 4, 4, 0x0, 0),
        }),
        new("PArray<PSceneRenderPass *>", "PBase", 8, 4, 0, 0, 0, 0x0, 0, new MemberRow[]
        {
            new("m_count", "PUInt32", 0, 4, 0x0, 0),
            new("m_els", "PSceneRenderPass", 4, 4, 0x2, 0),
        }),
        new("PArray<PSceneRenderPass>", "PBase", 8, 4, 0, 0, 0, 0x0, 0, new MemberRow[]
        {
            new("m_count", "PUInt32", 0, 4, 0x0, 0),
            new("m_els", "PSceneRenderPass", 4, 4, 0x0, 0),
        }),
        new("PArray<PShader>", "PBase", 8, 4, 0, 0, 0, 0x0, 0, new MemberRow[]
        {
            new("m_count", "PUInt32", 0, 4, 0x0, 0),
            new("m_els", "PShader", 4, 4, 0x0, 0),
        }),
        new("PArray<PShaderParameterCaptureBufferLocation>", "PBase", 8, 4, 0, 0, 0, 0x0, 0, new MemberRow[]
        {
            new("m_count", "PUInt32", 0, 4, 0x0, 0),
            new("m_els", "PShaderParameterCaptureBufferLocation", 4, 4, 0x0, 0),
        }),
        new("PArray<PShaderParameterCaptureBufferLocationTypeConstantBuffer>", "PBase", 8, 4, 0, 0, 0, 0x0, 0, new MemberRow[]
        {
            new("m_count", "PUInt32", 0, 4, 0x0, 0),
            new("m_els", "PShaderParameterCaptureBufferLocationTypeConstantBuffer", 4, 4, 0x0, 0),
        }),
        new("PArray<PShaderParameterDefinition>", "PBase", 8, 4, 0, 0, 0, 0x0, 0, new MemberRow[]
        {
            new("m_count", "PUInt32", 0, 4, 0x0, 0),
            new("m_els", "PShaderParameterDefinition", 4, 4, 0x0, 0),
        }),
        new("PArray<PShaderPass>", "PBase", 8, 4, 0, 0, 0, 0x0, 0, new MemberRow[]
        {
            new("m_count", "PUInt32", 0, 4, 0x0, 0),
            new("m_els", "PShaderPass", 4, 4, 0x0, 0),
        }),
        new("PArray<PShaderPassInfo>", "PBase", 8, 4, 0, 0, 0, 0x0, 0, new MemberRow[]
        {
            new("m_count", "PUInt32", 0, 4, 0x0, 0),
            new("m_els", "PShaderPassInfo", 4, 4, 0x0, 0),
        }),
        new("PArray<PShaderStreamDefinition>", "PBase", 8, 4, 0, 0, 0, 0x0, 0, new MemberRow[]
        {
            new("m_count", "PUInt32", 0, 4, 0x0, 0),
            new("m_els", "PShaderStreamDefinition", 4, 4, 0x0, 0),
        }),
        new("PArray<PShadowCasterType *>", "PBase", 8, 4, 0, 0, 0, 0x0, 0, new MemberRow[]
        {
            new("m_count", "PUInt32", 0, 4, 0x0, 0),
            new("m_els", "PShadowCasterType", 4, 4, 0x2, 0),
        }),
        new("PArray<PShadowSplit>", "PBase", 8, 4, 0, 0, 0, 0x0, 0, new MemberRow[]
        {
            new("m_count", "PUInt32", 0, 4, 0x0, 0),
            new("m_els", "PShadowSplit", 4, 4, 0x0, 0),
        }),
        new("PArray<PSkeletonJointBounds>", "PBase", 8, 4, 0, 0, 0, 0x0, 0, new MemberRow[]
        {
            new("m_count", "PUInt32", 0, 4, 0x0, 0),
            new("m_els", "PSkeletonJointBounds", 4, 4, 0x0, 0),
        }),
        new("PArray<PSkinBoneRemap>", "PBase", 8, 4, 0, 0, 0, 0x0, 0, new MemberRow[]
        {
            new("m_count", "PUInt32", 0, 4, 0x0, 0),
            new("m_els", "PSkinBoneRemap", 4, 4, 0x0, 0),
        }),
        new("PArray<PStreamInputDescD3D11>", "PBase", 8, 4, 0, 0, 0, 0x0, 0, new MemberRow[]
        {
            new("m_count", "PUInt32", 0, 4, 0x0, 0),
            new("m_els", "PStreamInputDescD3D11", 4, 4, 0x0, 0),
        }),
        new("PArray<PString>", "PBase", 8, 4, 0, 0, 0, 0x0, 0, new MemberRow[]
        {
            new("m_count", "PUInt32", 0, 4, 0x0, 0),
            new("m_els", "PString", 4, 4, 0x0, 0),
        }),
        new("PArray<PUInt32>", "PBase", 8, 4, 0, 0, 0, 0x0, 0, new MemberRow[]
        {
            new("m_count", "PUInt32", 0, 4, 0x0, 0),
            new("m_els", "PUInt32", 4, 4, 0x0, 0),
        }),
        new("PArray<PUInt8,4>", "PBase", 8, 4, 0, 0, 0, 0x0, 0, new MemberRow[]
        {
            new("m_count", "PUInt32", 0, 4, 0x0, 0),
            new("m_els", "PUInt8", 4, 4, 0x0, 0),
        }),
        new("PArray<PUInt8>", "PBase", 8, 4, 0, 0, 0, 0x0, 0, new MemberRow[]
        {
            new("m_count", "PUInt32", 0, 4, 0x0, 0),
            new("m_els", "PUInt8", 4, 4, 0x0, 0),
        }),
        new("PArray<PVertexStream>", "PBase", 8, 4, 0, 0, 0, 0x0, 0, new MemberRow[]
        {
            new("m_count", "PUInt32", 0, 4, 0x0, 0),
            new("m_els", "PVertexStream", 4, 4, 0x0, 0),
        }),
        new("PAssetReference", "PBase", 40, 4, 0, 0, 0, 0x8, 0, new MemberRow[]
        {
            new("m_id", "PString", 24, 4, 0x10, 0),
            new("m_asset", "PBase", 28, 4, 0x16, 0),
            new("m_assetType", "PClassDescriptor", 32, 4, 0x12, 0),
        }),
        new("PAssetReferenceImport", "PBase", 12, 4, 0, 0, 0, 0x0, 0, new MemberRow[]
        {
            new("m_id", "PString", 4, 4, 0x10, 0),
            new("m_targetAssetType", "PClassDescriptor", 0, 4, 0x12, 0),
        }),
        new("PBase", "-", 0, 1, 0, 0, 0, 0x0, 0, NoMembers),
        new("PCamera", "PBase", 188, 4, 0, 0, 0, 0x0, 0, new MemberRow[]
        {
            new("m_viewMatrix", "PMatrix4x3", 0, 48, 0x10, 0),
            new("m_projectionMatrix", "Matrix4", 48, 64, 0x10, 0),
            new("m_viewProjectionMatrix", "Matrix4", 112, 64, 0x10, 0),
            new("m_localToWorldMatrix", "PWorldMatrix", 176, 4, 0x12, 0),
            new("m_nearPlane", "float", 180, 4, 0x10, 0),
            new("m_farPlane", "float", 184, 4, 0x10, 0),
        }),
        new("PCameraOrthographic", "PCameraProjection", 200, 4, 0, 4, 4, 0x0, 0, new MemberRow[]
        {
            new("m_height", "float", 196, 4, 0x10, 0),
        }),
        new("PCameraPerspective", "PCameraProjection", 200, 4, 0, 4, 4, 0x0, 0, new MemberRow[]
        {
            new("m_FOV", "float", 196, 4, 0x10, 0),
        }),
        new("PCameraProjection", "PCamera", 196, 16, 4, 4, 4, 0x2, 0, new MemberRow[]
        {
            new("m_aspect", "float", 192, 4, 0x10, 0),
        }),
        new("PClassDescriptor", "PBase", 144, 16, 24, 24, 24, 0x2, 0, NoMembers),
        new("PClusterHeader", "PClusterHeaderD3D11", 84, 4, 0, 0, 0, 0x0, 0, NoMembers),
        new("PClusterHeaderBase", "PBase", 72, 4, 0, 0, 0, 0x0, 0, new MemberRow[]
        {
            new("m_phyreMarker", "PUInt32", 0, 4, 0x8, 0),
            new("m_size", "PUInt32", 4, 4, 0x8, 0),
            new("m_instanceListCount", "PUInt32", 16, 4, 0x8, 0),
            new("m_packedNamespaceSize", "PUInt32", 8, 4, 0x8, 0),
            new("m_arrayFixupSize", "PUInt32", 20, 4, 0x8, 0),
            new("m_arrayFixupCount", "PUInt32", 24, 4, 0x8, 0),
            new("m_pointerFixupSize", "PUInt32", 28, 4, 0x8, 0),
            new("m_pointerFixupCount", "PUInt32", 32, 4, 0x8, 0),
            new("m_pointerArrayFixupSize", "PUInt32", 36, 4, 0x8, 0),
            new("m_pointerArrayFixupCount", "PUInt32", 40, 4, 0x8, 0),
            new("m_pointersInArraysCount", "PUInt32", 44, 4, 0x8, 0),
            new("m_userFixupCount", "PUInt32", 48, 4, 0x8, 0),
            new("m_userFixupDataSize", "PUInt32", 52, 4, 0x8, 0),
            new("m_totalDataSize", "PUInt32", 56, 4, 0x8, 0),
            new("m_headerClassInstanceCount", "PUInt32", 60, 4, 0x8, 0),
            new("m_headerClassChildCount", "PUInt32", 64, 4, 0x8, 0),
            new("m_platformID", "PUInt32", 12, 4, 0x8, 0),
            new("m_physicsEngineID", "PUInt32", 68, 4, 0x8, 0),
        }),
        new("PClusterHeaderD3D11", "PClusterHeaderBase", 84, 4, 0, 0, 0, 0x0, 0, new MemberRow[]
        {
            new("m_indexBufferSize", "PUInt32", 72, 4, 0x0, 0),
            new("m_vertexBufferSize", "PUInt32", 76, 4, 0x0, 0),
            new("m_maxTextureBufferSize", "PUInt32", 80, 4, 0x0, 0),
        }),
        new("PContextVariantFoldingTable", "PBase", 20, 4, 0, 0, 0, 0x0, 0, new MemberRow[]
        {
            new("m_contextVariantIndex", "PUInt32", 0, 4, 0x0, 0),
            new("m_contextVariantVpIndex", "PUInt32", 4, 4, 0x0, 0),
            new("m_contextVariantFpIndex", "PUInt32", 8, 4, 0x0, 0),
            new("m_contextVariantGsIndex", "PUInt32", 12, 4, 0x0, 0),
            new("m_contextVariantCsIndex", "PUInt32", 16, 4, 0x0, 0),
        }),
        new("PDataBlockBase", "PBase", 24, 4, 0, 0, 0, 0x0, 0, new MemberRow[]
        {
            new("m_memoryType", "PUInt8", 21, 1, 0x10, 0),
            new("m_stride", "PUInt32", 0, 4, 0x10, 0),
            new("m_elementCount", "PUInt32", 4, 4, 0x10, 0),
            new("m_streams", "PArray<PVertexStream>", 8, 8, 0x10, 0),
        }),
        new("PDataBlockBufferD3D11", "PBase", 12, 4, 0, 0, 0, 0x0, 0, NoMembers),
        new("PDataBlockD3D11", "PDataBlockBase", 56, 4, 0, 0, 0, 0x0, 0, new MemberRow[]
        {
            new("m_buffers", "PSharray<PDataBlockBufferD3D11>", 24, 16, 0x0, 0),
            new("m_dataSize", "PUInt32", 48, 4, 0x0, 0),
            new("m_offsetInVertexBuffer", "PUInt32", 40, 4, 0x8, 0),
        }),
        new("PDynamicMesh", "PBase", 24, 16, 4, 4, 4, 0x2, 0, new MemberRow[]
        {
            new("m_dynamicStreams", "PArray<PVertexStream>", 8, 8, 0x8, 0),
            new("m_segments", "PArray<PDynamicSegmentDesc>", 16, 8, 0x8, 0),
            new("m_mesh", "PMesh", 4, 4, 0xA, 0),
        }),
        new("PDynamicMeshInstance", "PBase", 8, 4, 4, 4, 4, 0x8, 0, new MemberRow[]
        {
            new("m_dynamicMesh", "PDynamicMesh", 4, 4, 0xA, 0),
        }),
        new("PDynamicSegmentDesc", "PBase", 16, 4, 0, 0, 0, 0x0, 0, new MemberRow[]
        {
            new("m_startStreamIndex", "PUInt32", 0, 4, 0x8, 0),
            new("m_streamCount", "PUInt32", 4, 4, 0x8, 0),
            new("m_elementCount", "PUInt32", 8, 4, 0x8, 0),
            new("m_indexCount", "PInt32", 12, 4, 0x8, 0),
        }),
        new("PEffect", "PBase", 64, 4, 0, 0, 0, 0x0, 0, new MemberRow[]
        {
            new("m_supportedLightMask", "PUInt32", 0, 4, 0x0, 0),
            new("m_supportedShadowCasterMask", "PUInt32", 4, 4, 0x0, 0),
            new("m_effectFile", "PString", 8, 4, 0x0, 0),
            new("m_effectSource", "PString", 52, 4, 0x0, 0),
            new("m_effectVariants", "PArray<PEffectVariant *>", 12, 8, 0x0, 0),
            new("m_supportedLightTypes", "PArray<PLightType *>", 20, 8, 0x0, 0),
            new("m_supportedShadowCasterTypes", "PArray<PShadowCasterType *>", 28, 8, 0x0, 0),
            new("m_contextSwitches", "PArray<PContextSwitch *>", 36, 8, 0x0, 0),
            new("m_contextVariantSwitches", "PArray<PNodeContext>", 44, 8, 0x0, 0),
            new("m_maxLightCount", "PUInt32", 56, 4, 0x0, 0),
            new("m_numSupportedShaderLODLevels", "PUInt32", 60, 4, 0x0, 0),
        }),
        new("PEffectVariant", "PBase", 52, 4, 0, 0, 0, 0x8, 0, new MemberRow[]
        {
            new("m_effect", "PEffect", 0, 4, 0x2, 0),
            new("m_switches", "PArray<PMaterialSwitch>", 4, 8, 0x0, 0),
            new("m_sceneRenderPasses", "PArray<PSceneRenderPass>", 12, 8, 0x0, 0),
            new("m_sceneRenderPassLookup", "PArray<PSceneRenderPass *>", 20, 8, 0x0, 0),
            new("m_largestShaderPassCount", "PUInt16", 28, 2, 0x0, 0),
            new("m_tweakableShaderParameterDefinitions", "PArray<PShaderParameterDefinition>", 32, 8, 0x0, 0),
            new("m_untweakableShaderParameterDefinitions", "PArray<PShaderParameterDefinition>", 40, 8, 0x0, 0),
            new("m_tweakableParameterBufferSize", "PUInt16", 48, 2, 0x0, 0),
            new("m_untweakableParameterBufferSize", "PUInt16", 50, 2, 0x0, 0),
        }),
        new("PIndexDataBlockBase", "PBase", 20, 4, 0, 0, 0, 0x0, 0, new MemberRow[]
        {
            new("m_memoryType", "PUInt8", 13, 1, 0x10, 0),
            new("m_elementCount", "PUInt32", 8, 4, 0x10, 0),
            new("m_type", "PUInt8", 12, 1, 0x10, 0),
            new("m_minimumIndex", "PUInt32", 0, 4, 0x10, 0),
            new("m_maximumIndex", "PUInt32", 4, 4, 0x10, 0),
        }),
        new("PIndexDataBlockBufferD3D11", "PBase", 12, 4, 0, 0, 0, 0x0, 0, NoMembers),
        new("PIndexDataBlockD3D11", "PIndexDataBlockBase", 52, 4, 0, 0, 0, 0x0, 0, new MemberRow[]
        {
            new("m_buffers", "PSharray<PIndexDataBlockBufferD3D11>", 20, 16, 0x0, 0),
            new("m_dataSize", "PUInt32", 44, 4, 0x0, 0),
            new("m_offsetInIndexBuffer", "PUInt32", 36, 4, 0x8, 0),
        }),
        new("PInstanceListHeader", "PBase", 36, 4, 0, 0, 0, 0x0, 0, new MemberRow[]
        {
            new("m_classID", "PUInt32", 0, 4, 0x8, 0),
            new("m_count", "PUInt32", 4, 4, 0x8, 0),
            new("m_size", "PUInt32", 8, 4, 0x8, 0),
            new("m_objectsSize", "PUInt32", 12, 4, 0x8, 0),
            new("m_arraysSize", "PUInt32", 16, 4, 0x8, 0),
            new("m_pointersInArraysCount", "PUInt32", 20, 4, 0x8, 0),
            new("m_arrayFixupCount", "PUInt32", 24, 4, 0x8, 0),
            new("m_pointerFixupCount", "PUInt32", 28, 4, 0x8, 0),
            new("m_pointerArrayFixupCount", "PUInt32", 32, 4, 0x8, 0),
        }),
        new("PLight", "PBase", 52, 4, 0, 0, 0, 0x0, 0, new MemberRow[]
        {
            new("m_color", "Vector4", 0, 16, 0x10, 0),
            new("m_localToWorldMatrix", "PWorldMatrix", 16, 4, 0x12, 0),
            new("m_shadowCaster", "PShadowCaster", 20, 4, 0x12, 0),
            new("m_lightType", "PLightType", 24, 4, 0x12, 0),
            new("m_innerConeAngle", "float", 28, 4, 0x10, 0),
            new("m_outerConeAngle", "float", 32, 4, 0x10, 0),
            new("m_intensity", "float", 36, 4, 0x10, 0),
            new("m_innerRange", "float", 40, 4, 0x10, 0),
            new("m_outerRange", "float", 44, 4, 0x10, 0),
            new("m_scatteringIntensity", "float", 48, 4, 0x10, 0),
        }),
        new("PLocator", "PBase", 8, 4, 0, 0, 0, 0x0, 0, new MemberRow[]
        {
            new("m_name", "PString", 4, 4, 0x0, 0),
            new("m_localToWorldMatrix", "PWorldMatrix", 0, 4, 0x2, 0),
        }),
        new("PLODGroup", "PBase", 72, 4, 0, 0, 0, 0x0, 0, new MemberRow[]
        {
            new("m_levels", "PArray<PLODLevel>", 60, 8, 0x0, 0),
            new("m_minBounds", "Vector3", 0, 16, 0x0, 0),
            new("m_maxBounds", "Vector3", 16, 16, 0x0, 0),
            new("m_blendRange", "float", 40, 4, 0x0, 0),
            new("m_shaderLODLevelDistance", "float", 44, 4, 0x0, 0),
            new("m_lodMetricType", "PLODMetricType", 52, 4, 0x2, 0),
            new("m_lodBlendType", "PLODBlendType", 56, 4, 0x2, 0),
            new("m_isEnabled", "bool", 68, 1, 0x0, 0),
        }),
        new("PLODLevel", "PBase", 36, 4, 0, 0, 0, 0x0, 0, new MemberRow[]
        {
            new("m_lodGroup", "PLODGroup", 0, 4, 0x2, 0),
            new("m_meshInstances", "PSharray<PMeshInstance *>", 4, 8, 0x0, 0),
            new("m_minimumThreshold", "float", 12, 4, 0x0, 0),
            new("m_maximumThreshold", "float", 16, 4, 0x0, 0),
        }),
        new("PMaterial", "PBase", 16, 4, 0, 0, 0, 0x8, 0, new MemberRow[]
        {
            new("m_effectVariant", "PEffectVariant", 0, 4, 0x2, 0),
            new("m_parameterBuffer", "PParameterBuffer", 4, 4, 0x2, 0),
            new("m_remapFrom", "PSceneRenderPassType", 8, 4, 0x2, 0),
            new("m_remapTo", "PSceneRenderPassType", 12, 4, 0x2, 0),
        }),
        new("PMaterialSet", "PBase", 8, 4, 0, 0, 0, 0x0, 0, new MemberRow[]
        {
            new("m_materials", "PSharray<PMaterial *>", 0, 8, 0x8, 0),
        }),
        new("PMaterialSwitch", "PBase", 8, 4, 0, 0, 0, 0x0, 0, new MemberRow[]
        {
            new("m_name", "PString", 0, 4, 0x0, 0),
            new("m_value", "PString", 4, 4, 0x0, 0),
        }),
        new("PMatrix4", "-", 64, 4, 0, 0, 0, 0x0, 0, new MemberRow[]
        {
            new("m_elements", "float", 0, 4, 0x0, 16),
        }),
        new("PMatrix4x3", "-", 48, 4, 0, 0, 0, 0x0, 0, new MemberRow[]
        {
            new("m_elements", "float", 0, 4, 0x0, 12),
        }),
        new("PMesh", "PBase", 56, 4, 0, 0, 0, 0x0, 0, new MemberRow[]
        {
            new("m_meshSegments", "PArray<PMeshSegment>", 0, 8, 0x8, 0),
            new("m_skeletonMatrices", "PArray<PMatrix4>", 8, 8, 0x8, 0),
            new("m_skeletonBounds", "PArray<PSkeletonJointBounds>", 16, 8, 0x8, 0),
            new("m_defaultPose", "PArray<PMatrix4>", 24, 8, 0x8, 0),
            new("m_matrixNames", "PArray<PString>", 32, 8, 0x8, 0),
            new("m_matrixParents", "PArray<PInt32>", 40, 8, 0x8, 0),
            new("m_defaultMaterials", "PMaterialSet", 48, 8, 0x8, 0),
        }),
        new("PMeshInstance", "PBase", 64, 4, 0, 0, 0, 0x8, 0, new MemberRow[]
        {
            new("m_mesh", "PMesh", 0, 4, 0xA, 0),
            new("m_localToWorldMatrix", "PWorldMatrix", 4, 4, 0xA, 0),
            new("m_currentPose", "PArray<PMatrix4>", 8, 8, 0x8, 0),
            new("m_materialSet", "PMaterialSet", 16, 4, 0xA, 0),
            new("m_instanceSegment", "PMeshSegment", 20, 4, 0xA, 0),
            new("m_dynamicMeshInstance", "PDynamicMeshInstance", 24, 4, 0xA, 0),
            new("m_bounds", "PMeshInstanceBounds", 28, 4, 0xA, 0),
            new("m_lodLevel", "PLODLevel", 32, 4, 0xA, 0),
            new("m_segmentContext", "PArray<PMeshInstanceSegmentContext>", 36, 8, 0x8, 0),
            new("m_exFlags", "PUInt32", 44, 4, 0x8, 0),
            new("m_edgeParameters", "Vector4", 48, 16, 0x8, 0),
            new("m_nodeMaterialDiffuse", "Vector4", 64, 16, 0x8, 0),
            new("m_nodeMaterialEmission", "Vector4", 80, 16, 0x8, 0),
            new("m_gameMaterialIDs", "PArray<PUInt32>", 96, 8, 0x8, 0),
            new("m_drawOrder", "float", 104, 4, 0x8, 0),
        }),
        new("PMeshInstanceAttachPoint", "PBase", 12, 4, 0, 0, 0, 0x8, 0, new MemberRow[]
        {
            new("m_destination", "PWorldMatrix", 0, 4, 0x2, 0),
            new("m_source", "PMeshInstance", 4, 4, 0x2, 0),
            new("m_sourceMatrixIndex", "PUInt32", 8, 4, 0x0, 0),
        }),
        new("PMeshInstanceBounds", "PBase", 32, 4, 0, 0, 0, 0x0, 0, new MemberRow[]
        {
            new("m_meshInstance", "PMeshInstance", 28, 4, 0x2, 0),
            new("m_worldMatrix", "PWorldMatrix", 12, 4, 0x2, 0),
            new("m_min", "float", 0, 4, 0x0, 3),
            new("m_size", "float", 16, 4, 0x0, 3),
        }),
        new("PMeshInstanceSegmentContext", "PMeshSegmentContext", 36, 4, 0, 0, 0, 0x0, 0, new MemberRow[]
        {
            new("m_streamBindings", "PSharray<PMeshInstanceSegmentStreamBinding *>", 28, 8, 0x8, 0),
        }),
        new("PMeshInstanceSegmentStreamBinding", "PBase", 12, 4, 0, 0, 0, 0x0, 0, new MemberRow[]
        {
            new("m_renderDataType", "PRenderDataType", 0, 4, 0xA, 0),
            new("m_name", "PString", 4, 4, 0x8, 0),
            new("m_nameHash", "PUInt16", 8, 2, 0x8, 0),
            new("m_index", "PUInt8", 10, 1, 0x8, 0),
            new("m_inputSet", "PUInt8", 11, 1, 0x8, 0),
        }),
        new("PMeshSegment", "PMeshSegmentD3D11", 80, 4, 0, 0, 0, 0x0, 0, NoMembers),
        new("PMeshSegmentBase", "PBase", 20, 4, 0, 0, 0, 0x0, 0, new MemberRow[]
        {
            new("m_materialIndex", "PUInt32", 0, 4, 0x10, 0),
            new("m_matrixIndex", "PInt32", 4, 4, 0x10, 0),
            new("m_skinBones", "PArray<PSkinBoneRemap>", 8, 8, 0x10, 0),
            new("m_primitiveType", "PInt32", 16, 4, 0x30, 0),
        }),
        new("PMeshSegmentContext", "PBase", 20, 4, 0, 0, 0, 0x0, 0, NoMembers),
        new("PMeshSegmentD3D11", "PMeshSegmentBase", 80, 4, 0, 0, 0, 0x0, 0, new MemberRow[]
        {
            new("m_vertexData", "PArray<PDataBlockD3D11>", 20, 8, 0x10, 0),
            new("m_indexData", "PIndexDataBlockD3D11", 28, 52, 0x10, 0),
        }),
        new("PNode", "PBase", 84, 4, 4, 4, 4, 0x0, 0, new MemberRow[]
        {
            new("m_parent", "PNode", 4, 4, 0x12, 0),
            new("m_firstChild", "PNode", 8, 4, 0x12, 0),
            new("m_next", "PNode", 0, 4, 0x12, 0),
            new("m_worldMatrix", "PWorldMatrix", 12, 4, 0x12, 0),
            new("m_localMatrix", "PMatrix4", 16, 64, 0x10, 0),
            new("m_name", "PString", 80, 4, 0x10, 0),
        }),
        new("PNodeContext", "PBase", 8, 4, 0, 0, 0, 0x0, 0, new MemberRow[]
        {
            new("m_packedSwitches", "PSharray<PUInt32>", 0, 8, 0x8, 0),
        }),
        new("Point3", "-", 16, 4, 0, 0, 0, 0x0, 0, new MemberRow[]
        {
            new("m_elements", "float", 0, 4, 0x0, 4),
        }),
        new("PParameterBuffer", "PParameterBufferBase", 16, 4, 0, 0, 0, 0xC, 0, new MemberRow[]
        {
            new("m_effectVariant", "PEffectVariant", 4, 4, 0x2, 0),
            new("m_tweakableShaderParameterDefinitions", "PArray<PShaderParameterDefinition>", 8, 8, 0x0, 0),
        }),
        new("PParameterBufferBase", "PBase", 4, 16, 0, 0, 0, 0x2, 0, new MemberRow[]
        {
            new("m_parameterBufferSize", "PUInt32", 0, 4, 0x0, 0),
        }),
        new("PPhysicsCharacterControllerBase", "PBase", 268, 4, 0, 0, 0, 0x0, 0, new MemberRow[]
        {
            new("m_gravity", "Vector3", 36, 16, 0x8, 0),
            new("m_targetNode", "PNode", 196, 4, 0xA, 0),
            new("m_targetWorldMatrix", "PWorldMatrix", 200, 4, 0xA, 0),
            new("m_rotate", "float", 208, 4, 0x8, 0),
            new("m_right", "float", 212, 4, 0x8, 0),
            new("m_forward", "float", 216, 4, 0x8, 0),
            new("m_velocity", "float", 220, 4, 0x8, 0),
            new("m_jump", "bool", 244, 1, 0x8, 0),
            new("m_isOnGround", "bool", 245, 1, 0x8, 0),
            new("m_maxSlopeAngle", "float", 224, 4, 0x8, 0),
            new("m_next", "PPhysicsCharacterControllerBase", 0, 4, 0xA, 0),
            new("m_startPosition", "Point3", 4, 16, 0x8, 0),
            new("m_scale", "Vector3", 20, 16, 0x8, 0),
            new("m_jumpHeight", "float", 228, 4, 0x8, 0),
            new("m_height", "float", 232, 4, 0x8, 0),
            new("m_radius", "float", 236, 4, 0x8, 0),
            new("m_world", "PPhysicsWorld", 204, 4, 0xA, 0),
            new("m_graphicsOffset", "PMatrix4", 68, 64, 0x8, 0),
            new("m_invGraphicsOffset", "PMatrix4", 132, 64, 0x8, 0),
            new("m_scriptHandler", "PScriptCallbackHandler", 256, 12, 0x8, 0),
        }),
        new("PPhysicsMaterial", "PBase", 12, 4, 0, 0, 0, 0x0, 0, new MemberRow[]
        {
            new("m_dynamicFriction", "float", 0, 4, 0x8, 0),
            new("m_staticFriction", "float", 4, 4, 0x8, 0),
            new("m_restitution", "float", 8, 4, 0x8, 0),
        }),
        new("PPhysicsMesh", "PPhysicsMeshBullet", 108, 4, 0, 4, 4, 0x0, 0, NoMembers),
        new("PPhysicsMeshBase", "PPhysicsShape", 96, 4, 0, 4, 4, 0x0, 0, new MemberRow[]
        {
            new("m_shape", "PShape", 92, 4, 0xA, 0),
        }),
        new("PPhysicsMeshBullet", "PPhysicsMeshBase", 108, 4, 0, 4, 4, 0x0, 0, NoMembers),
        new("PPhysicsModel", "PBase", 12, 4, 0, 0, 0, 0x0, 0, new MemberRow[]
        {
            new("m_rigidBodies", "PPhysicsRigidBody", 4, 4, 0xA, 0),
            new("m_next", "PPhysicsModel", 0, 4, 0xA, 0),
            new("m_world", "PPhysicsWorld", 8, 4, 0xA, 0),
        }),
        new("PPhysicsRigidBody", "PPhysicsRigidBodyBullet", 228, 4, 0, 0, 0, 0x0, 0, NoMembers),
        new("PPhysicsRigidBodyBase", "PBase", 220, 4, 0, 0, 0, 0x0, 0, new MemberRow[]
        {
            new("m_mass", "float", 192, 4, 0x8, 0),
            new("m_rigidBodyType", "PUInt8", 196, 1, 0x8, 0),
            new("m_massFrameTransform", "PMatrix4x3", 4, 48, 0x8, 0),
            new("m_initialPosition", "Vector3", 52, 16, 0x8, 0),
            new("m_initialOrientation", "Quat", 68, 16, 0x8, 0),
            new("m_inertiaTensor", "Vector3", 84, 16, 0x8, 0),
            new("m_initialLinearVelocity", "Vector3", 100, 16, 0x8, 0),
            new("m_initialAngularVelocity", "Vector3", 116, 16, 0x8, 0),
            new("m_targetNode", "PNode", 152, 4, 0xA, 0),
            new("m_targetWorldMatrix", "PWorldMatrix", 156, 4, 0xA, 0),
            new("m_material", "PPhysicsMaterial", 148, 4, 0xA, 0),
            new("m_shapes", "PSharray<PPhysicsShape *>", 160, 8, 0x8, 0),
            new("m_scale", "Vector3", 132, 16, 0x8, 0),
            new("m_linearDamping", "float", 168, 4, 0x8, 0),
            new("m_angularDamping", "float", 172, 4, 0x8, 0),
            new("m_next", "PPhysicsRigidBody", 0, 4, 0xA, 0),
            new("m_model", "PPhysicsModel", 176, 4, 0xA, 0),
            new("m_nextKinematicRigidBody", "PPhysicsRigidBody", 184, 4, 0xA, 0),
            new("m_collisionGroup", "PUInt8", 188, 1, 0x8, 0),
            new("m_enabled", "bool", 197, 1, 0x8, 0),
            new("m_scriptHandler", "PScriptCallbackHandler", 208, 12, 0x8, 0),
        }),
        new("PPhysicsRigidBodyBullet", "PPhysicsRigidBodyBase", 228, 4, 0, 0, 0, 0x0, 0, NoMembers),
        new("PPhysicsShape", "PPhysicsShapeBullet", 92, 4, 0, 4, 4, 0x0, 0, NoMembers),
        new("PPhysicsShapeBase", "PBase", 88, 16, 4, 4, 4, 0x2, 0, new MemberRow[]
        {
            new("m_hollow", "bool", 4, 1, 0x8, 0),
            new("m_mass", "float", 8, 4, 0x8, 0),
            new("m_density", "float", 12, 4, 0x8, 0),
            new("m_material", "PPhysicsMaterial", 16, 4, 0xA, 0),
            new("m_transform", "PMatrix4x3", 20, 48, 0x8, 0),
            new("m_scale", "Vector3", 68, 16, 0x8, 0),
            new("m_type", "PInt32", 84, 4, 0x28, 0),
        }),
        new("PPhysicsShapeBullet", "PPhysicsShapeBase", 92, 4, 0, 4, 4, 0x0, 0, NoMembers),
        new("PPhysicsWorld", "PPhysicsWorldBullet", 168, 4, 0, 0, 0, 0x0, 0, NoMembers),
        new("PPhysicsWorldBase", "PBase", 84, 4, 0, 0, 0, 0x0, 0, new MemberRow[]
        {
            new("m_models", "PPhysicsModel", 72, 4, 0xA, 0),
            new("m_gravity", "Vector3", 0, 16, 0x8, 0),
            new("m_timeStep", "float", 16, 4, 0x8, 0),
            new("m_worldMin", "Vector3", 20, 16, 0x8, 0),
            new("m_worldMax", "Vector3", 36, 16, 0x8, 0),
            new("m_characterControllers", "PPhysicsCharacterControllerBase", 76, 4, 0xA, 0),
            new("m_kinematicRigidBodies", "PPhysicsRigidBody", 80, 4, 0xA, 0),
        }),
        new("PPhysicsWorldBullet", "PPhysicsWorldBase", 168, 4, 0, 0, 0, 0x0, 0, NoMembers),
        new("PSamplerState", "PSamplerStateD3D11", 36, 4, 0, 0, 0, 0x0, 0, NoMembers),
        new("PSamplerStateBase", "PBase", 32, 4, 0, 0, 0, 0x0, 0, new MemberRow[]
        {
            new("m_minFilter", "PUInt8", 0, 1, 0x10, 0),
            new("m_magFilter", "PUInt8", 1, 1, 0x10, 0),
            new("m_wrapS", "PUInt8", 2, 1, 0x10, 0),
            new("m_wrapT", "PUInt8", 3, 1, 0x10, 0),
            new("m_wrapR", "PUInt8", 4, 1, 0x10, 0),
            new("m_lodBias", "float", 8, 4, 0x10, 0),
            new("m_maxAnisotropy", "float", 12, 4, 0x10, 0),
            new("m_borderColor", "PUInt32", 16, 4, 0x10, 0),
            new("m_baseLevel", "PUInt32", 20, 4, 0x10, 0),
            new("m_maxLevel", "PUInt32", 24, 4, 0x10, 0),
            new("m_flags", "PUInt32", 28, 4, 0x10, 0),
        }),
        new("PSamplerStateD3D11", "PSamplerStateBase", 36, 4, 0, 0, 0, 0x0, 0, NoMembers),
        new("PSceneRenderPass", "PBase", 40, 4, 0, 0, 0, 0x0, 0, new MemberRow[]
        {
            new("m_passType", "PSceneRenderPassType", 0, 4, 0x2, 0),
            new("m_shaders", "PArray<PShader>", 4, 8, 0x0, 0),
            new("m_entryPoints", "PArray<PShaderPassInfo>", 12, 8, 0x0, 0),
            new("m_variantsFoldingTable", "PArray<PContextVariantFoldingTable>", 20, 8, 0x0, 0),
            new("m_platforms", "PArray<PString>", 28, 8, 0x0, 0),
            new("m_platformsAreInclude", "bool", 36, 1, 0x0, 0),
        }),
        new("PScriptCallbackHandler", "PBase", 12, 4, 0, 0, 0, 0x0, 0, new MemberRow[]
        {
            new("m_entryPoint", "PString", 0, 4, 0x0, 0),
            new("m_handler", "PTypedObject", 4, 8, 0x0, 0),
        }),
        new("PShader", "PBase", 32, 4, 0, 0, 0, 0x0, 0, new MemberRow[]
        {
            new("m_passes", "PArray<PShaderPass>", 4, 8, 0x0, 0),
            new("m_parameterDefinitionsForPasses", "PArray<PShaderParameterDefinition>", 12, 8, 0x0, 0),
            new("m_streamDefinitionsForPasses", "PArray<PShaderStreamDefinition>", 20, 8, 0x0, 0),
            new("m_parameterBufferSize", "PUInt32", 28, 4, 0x0, 0),
            new("m_parameterBufferFrequenciesRequired", "PUInt32", 0, 4, 0x0, 0),
        }),
        new("PShaderComputeProgram", "PShaderComputeProgramD3D11", 1252, 4, 0, 0, 0, 0x8, 0, NoMembers),
        new("PShaderComputeProgramD3D11", "PShaderProgramD3D11", 1252, 4, 0, 0, 0, 0x8, 0, NoMembers),
        new("PShaderFragmentProgram", "PShaderFragmentProgramD3D11", 1252, 4, 0, 0, 0, 0x8, 0, NoMembers),
        new("PShaderFragmentProgramD3D11", "PShaderProgramD3D11", 1252, 4, 0, 0, 0, 0x8, 0, NoMembers),
        new("PShaderGeometryProgram", "PShaderGeometryProgramD3D11", 1252, 4, 0, 0, 0, 0x8, 0, NoMembers),
        new("PShaderGeometryProgramD3D11", "PShaderProgramD3D11", 1252, 4, 0, 0, 0, 0x8, 0, NoMembers),
        new("PShaderParameterCaptureBufferLocation", "PBase", 2, 2, 0, 0, 0, 0x0, 0, new MemberRow[]
        {
            new("m_offset", "PUInt16", 0, 2, 0x0, 0),
        }),
        new("PShaderParameterCaptureBufferLocationSize", "PShaderParameterCaptureBufferLocation", 4, 2, 0, 0, 0, 0x0, 0, new MemberRow[]
        {
            new("m_size", "PUInt16", 2, 2, 0x0, 0),
        }),
        new("PShaderParameterCaptureBufferLocationTypeConstantBuffer", "PShaderParameterCaptureBufferLocation", 16, 4, 0, 0, 0, 0x0, 0, new MemberRow[]
        {
            new("m_constantBufferLocation", "PUInt32", 4, 4, 0x0, 0),
            new("m_size", "PUInt32", 8, 4, 0x0, 0),
            new("m_type", "PUInt8", 12, 1, 0x0, 0),
        }),
        new("PShaderParameterCaptureBufferSampler", "PShaderParameterCaptureBufferTextureBase", 16, 4, 0, 0, 0, 0x0, 0, new MemberRow[]
        {
            new("m_unusedPointer", "PTextureCommonBase", 12, 4, 0x12, 0),
        }),
        new("PShaderParameterCaptureBufferTexture2D", "PShaderParameterCaptureBufferTextureBase", 16, 4, 0, 0, 0, 0x0, 0, new MemberRow[]
        {
            new("m_texture", "PTexture2D", 12, 4, 0x12, 0),
        }),
        new("PShaderParameterCaptureBufferTextureBase", "PBase", 12, 4, 0, 0, 0, 0x8, 0, new MemberRow[]
        {
            new("m_parameterType", "PUInt32", 0, 4, 0x10, 0),
            new("m_samplerState", "PSamplerState", 8, 4, 0x12, 0),
            new("m_textureBufferIndex", "PUInt32", 4, 4, 0x10, 0),
        }),
        new("PShaderParameterDefinition", "PBase", 16, 4, 0, 0, 0, 0x0, 0, new MemberRow[]
        {
            new("m_name", "PString", 4, 4, 0x0, 0),
            new("m_parameterType", "PUInt8", 2, 1, 0x0, 0),
            new("m_dataType", "PUInt8", 3, 1, 0x0, 0),
            new("m_arrayElementCount", "PUInt16", 0, 2, 0x0, 0),
            new("m_bufferLoc", "PShaderParameterCaptureBufferLocationSize", 8, 4, 0x0, 0),
            new("m_constantBufferLocation", "PUInt32", 12, 4, 0x0, 0),
        }),
        new("PShaderPass", "PShaderPassD3D11", 596, 4, 0, 0, 0, 0x0, 0, NoMembers),
        new("PShaderPassBase", "PBase", 24, 4, 0, 0, 0, 0x0, 0, new MemberRow[]
        {
            new("m_vertexProgram", "PShaderVertexProgram", 0, 4, 0x12, 0),
            new("m_fragmentProgram", "PShaderFragmentProgram", 4, 4, 0x12, 0),
            new("m_geometryProgram", "PShaderGeometryProgram", 8, 4, 0x12, 0),
            new("m_computeProgram", "PShaderComputeProgram", 12, 4, 0x12, 0),
            new("m_streamLocations", "PArray<PShaderParameterCaptureBufferLocation>", 16, 8, 0x10, 0),
        }),
        new("PShaderPassD3D11", "PShaderPassBase", 596, 4, 0, 0, 0, 0x0, 0, new MemberRow[]
        {
            new("m_state", "PShaderPassStateD3D11", 24, 380, 0x10, 0),
            new("m_vertexParameterLocation", "PShaderPassParameterLocationTypesConstantBuffer", 404, 24, 0x10, 0),
            new("m_fragmentParameterLocation", "PShaderPassParameterLocationTypesConstantBuffer", 428, 24, 0x10, 0),
            new("m_geometryParameterLocation", "PShaderPassParameterLocationTypesConstantBuffer", 452, 24, 0x10, 0),
            new("m_computeParameterLocation", "PShaderPassParameterLocationTypesConstantBuffer", 476, 24, 0x10, 0),
            new("m_vertexTexParameterLocation", "PShaderPassParameterLocationTypesConstantBuffer", 500, 24, 0x10, 0),
            new("m_fragmentTexParameterLocation", "PShaderPassParameterLocationTypesConstantBuffer", 524, 24, 0x10, 0),
            new("m_geometryTexParameterLocation", "PShaderPassParameterLocationTypesConstantBuffer", 548, 24, 0x10, 0),
            new("m_computeTexParameterLocation", "PShaderPassParameterLocationTypesConstantBuffer", 572, 24, 0x10, 0),
        }),
        new("PShaderPassInfo", "PBase", 32, 4, 0, 0, 0, 0x0, 0, new MemberRow[]
        {
            new("m_vertexEntryPoint", "PString", 0, 4, 0x0, 0),
            new("m_vertexProfile", "PUInt32", 16, 4, 0x0, 0),
            new("m_fragmentEntryPoint", "PString", 4, 4, 0x0, 0),
            new("m_fragmentProfile", "PUInt32", 20, 4, 0x0, 0),
            new("m_geometryEntryPoint", "PString", 8, 4, 0x0, 0),
            new("m_geometryProfile", "PUInt32", 24, 4, 0x0, 0),
            new("m_computeEntryPoint", "PString", 12, 4, 0x0, 0),
            new("m_computeProfile", "PUInt32", 28, 4, 0x0, 0),
        }),
        new("PShaderPassParameterLocationTypesBase", "PBase", 16, 2, 0, 0, 0, 0x0, 0, new MemberRow[]
        {
            new("m_parameterStart", "PUInt16", 0, 2, 0x10, 4),
            new("m_parameterCount", "PUInt16", 8, 2, 0x10, 4),
        }),
        new("PShaderPassParameterLocationTypesConstantBuffer", "PShaderPassParameterLocationTypesBase", 24, 4, 0, 0, 0, 0x0, 0, new MemberRow[]
        {
            new("m_parameterLocations", "PArray<PShaderParameterCaptureBufferLocationTypeConstantBuffer>", 16, 8, 0x10, 0),
        }),
        new("PShaderPassStateBase", "PBase", 4, 4, 0, 0, 0, 0x0, 0, new MemberRow[]
        {
            new("m_importantState", "PUInt32", 0, 4, 0x10, 0),
        }),
        new("PShaderPassStateD3D11", "PShaderPassStateBase", 380, 4, 0, 0, 0, 0x0, 0, new MemberRow[]
        {
            new("m_rasterDesc", "CD3D11_RASTERIZER_DESC", 4, 40, 0x10, 0),
            new("m_depthDesc", "CD3D11_DEPTH_STENCIL_DESC", 44, 52, 0x10, 0),
            new("m_blendDesc", "CD3D11_BLEND_DESC", 96, 264, 0x10, 0),
            new("m_stencilRef", "PUInt8", 376, 1, 0x10, 0),
        }),
        new("PShaderProgramBase", "PBase", 1, 1, 0, 0, 0, 0x0, 0, NoMembers),
        new("PShaderProgramD3D11", "PShaderProgramBase", 1248, 4, 0, 0, 0, 0x8, 0, new MemberRow[]
        {
            new("m_compiledCode", "PArray<PUInt8>", 12, 8, 0x10, 0),
            new("m_constantBufferSize", "PUInt32", 20, 4, 0x10, 0),
            new("m_globalConstantBufferIndex", "PUInt32", 24, 4, 0x10, 0),
            new("m_shaderProfile", "PUInt32", 1244, 4, 0x10, 0),
        }),
        new("PShaderStreamDefinition", "PBase", 16, 4, 0, 0, 0, 0x0, 0, new MemberRow[]
        {
            new("m_name", "PString", 4, 4, 0x10, 0),
            new("m_dataType", "PUInt8", 14, 1, 0x10, 0),
            new("m_renderType", "PRenderDataType", 0, 4, 0x12, 0),
            new("m_bufferLoc", "PShaderParameterCaptureBufferLocationSize", 8, 4, 0x10, 0),
            new("m_nameHash", "PUInt16", 12, 2, 0x10, 0),
            new("m_index", "PUInt8", 15, 1, 0x10, 0),
        }),
        new("PShaderVertexProgram", "PShaderVertexProgramD3D11", 1264, 4, 0, 0, 0, 0x8, 0, NoMembers),
        new("PShaderVertexProgramD3D11", "PShaderProgramD3D11", 1264, 4, 0, 0, 0, 0x8, 0, new MemberRow[]
        {
            new("m_inputLayout", "PStreamInputLayoutD3D11", 1248, 12, 0x10, 0),
        }),
        new("PShadowCaster", "PBase", 104, 4, 0, 0, 0, 0x0, 0, new MemberRow[]
        {
            new("m_splits", "PArray<PShadowSplit>", 8, 8, 0x10, 0),
            new("m_shadowCasterType", "PShadowCasterType", 4, 4, 0x12, 0),
            new("m_zbias", "float", 64, 4, 0x10, 0),
            new("m_light", "PLight", 0, 4, 0x12, 0),
        }),
        new("PShadowSplit", "PBase", 224, 4, 0, 0, 0, 0x0, 0, new MemberRow[]
        {
            new("m_farPlane", "float", 196, 4, 0x10, 0),
        }),
        new("PShape", "PBase", 28, 4, 0, 0, 0, 0x0, 0, new MemberRow[]
        {
            new("m_indices", "PArray<PUInt8,4>", 4, 8, 0x8, 0),
            new("m_indexFormat", "PUInt8", 25, 1, 0x8, 0),
            new("m_indexCount", "PUInt32", 0, 4, 0x8, 0),
            new("m_vertexData", "PArray<PUInt8,4>", 16, 8, 0x8, 0),
            new("m_vertexFormat", "PUInt8", 24, 1, 0x8, 0),
            new("m_vertexCount", "PUInt32", 12, 4, 0x8, 0),
        }),
        new("PSharray<PAnimationClip *>", "PBase", 8, 4, 0, 0, 0, 0x0, 0, new MemberRow[]
        {
            new("m_u", "PAnimationClip", 4, 4, 0x42, 0),
            new("m_count", "PUInt32", 0, 4, 0x0, 0),
        }),
        new("PSharray<PDataBlockBufferD3D11>", "PBase", 16, 4, 0, 0, 0, 0x0, 0, new MemberRow[]
        {
            new("m_u", "PDataBlockBufferD3D11", 4, 12, 0x40, 0),
            new("m_count", "PUInt32", 0, 4, 0x0, 0),
        }),
        new("PSharray<PIndexDataBlockBufferD3D11>", "PBase", 16, 4, 0, 0, 0, 0x0, 0, new MemberRow[]
        {
            new("m_u", "PIndexDataBlockBufferD3D11", 4, 12, 0x40, 0),
            new("m_count", "PUInt32", 0, 4, 0x0, 0),
        }),
        new("PSharray<PMaterial *>", "PBase", 8, 4, 0, 0, 0, 0x0, 0, new MemberRow[]
        {
            new("m_u", "PMaterial", 4, 4, 0x42, 0),
            new("m_count", "PUInt32", 0, 4, 0x0, 0),
        }),
        new("PSharray<PMeshInstance *>", "PBase", 8, 4, 0, 0, 0, 0x0, 0, new MemberRow[]
        {
            new("m_u", "PMeshInstance", 4, 4, 0x42, 0),
            new("m_count", "PUInt32", 0, 4, 0x0, 0),
        }),
        new("PSharray<PMeshInstanceSegmentStreamBinding *>", "PBase", 8, 4, 0, 0, 0, 0x0, 0, new MemberRow[]
        {
            new("m_u", "PMeshInstanceSegmentStreamBinding", 4, 4, 0x42, 0),
            new("m_count", "PUInt32", 0, 4, 0x0, 0),
        }),
        new("PSharray<PPhysicsShape *>", "PBase", 8, 4, 0, 0, 0, 0x0, 0, new MemberRow[]
        {
            new("m_u", "PPhysicsShape", 4, 4, 0x42, 0),
            new("m_count", "PUInt32", 0, 4, 0x0, 0),
        }),
        new("PSharray<PUInt32>", "PBase", 8, 4, 0, 0, 0, 0x0, 0, new MemberRow[]
        {
            new("m_u", "PUInt32", 4, 4, 0x40, 0),
            new("m_count", "PUInt32", 0, 4, 0x0, 0),
        }),
        new("PSkeletonJointBounds", "PBase", 32, 4, 0, 0, 0, 0x0, 0, new MemberRow[]
        {
            new("m_min", "float", 0, 4, 0x8, 3),
            new("m_size", "float", 16, 4, 0x8, 3),
            new("m_hierarchyMatrixIndex", "PUInt32", 12, 4, 0x8, 0),
            new("m_pad", "PUInt32", 28, 4, 0x8, 0),
        }),
        new("PSkinBoneRemap", "PBase", 4, 2, 0, 0, 0, 0x0, 0, new MemberRow[]
        {
            new("m_hierarchyMatrixIndex", "PUInt16", 0, 2, 0x10, 0),
            new("m_skeletonMatrixIndex", "PUInt16", 2, 2, 0x10, 0),
        }),
        new("PStreamInputDescD3D11", "PBase", 20, 4, 0, 0, 0, 0x0, 0, new MemberRow[]
        {
            new("m_semantic", "PString", 0, 4, 0x10, 0),
            new("m_renderType", "PRenderDataType", 4, 4, 0x12, 0),
            new("m_semanticIndex", "PUInt32", 8, 4, 0x10, 0),
            new("m_d3dFormat", "PUInt32", 12, 4, 0x10, 0),
            new("m_inputSlot", "PUInt32", 16, 4, 0x10, 0),
        }),
        new("PStreamInputLayoutD3D11", "PBase", 12, 4, 0, 0, 0, 0x8, 0, new MemberRow[]
        {
            new("m_streams", "PArray<PStreamInputDescD3D11>", 0, 8, 0x10, 0),
        }),
        new("PString", "PBase", 4, 4, 0, 0, 0, 0x0, 0, new MemberRow[]
        {
            new("m_buffer", "PChar", 0, 4, 0x10, 0),
        }),
        new("PTexture2D", "PTexture2DD3D11", 112, 4, 0, 0, 0, 0x0, 0, NoMembers),
        new("PTexture2DBase", "PTextureCommonBase", 36, 4, 0, 0, 0, 0x0, 0, new MemberRow[]
        {
            new("m_width", "PUInt32", 28, 4, 0x10, 0),
            new("m_height", "PUInt32", 32, 4, 0x10, 0),
        }),
        new("PTexture2DD3D11", "PTexture2DBase", 112, 4, 0, 0, 0, 0x0, 0, NoMembers),
        new("PTextureCommonBase", "PBase", 28, 4, 0, 0, 0, 0x0, 0, new MemberRow[]
        {
            new("m_format", "PTextureFormatBase", 0, 4, 0x12, 0),
            new("m_memoryType", "PUInt8", 5, 1, 0x10, 0),
            new("m_mipmapCount", "PUInt32", 12, 4, 0x10, 0),
            new("m_maxMipLevel", "PUInt32", 16, 4, 0x10, 0),
            new("m_textureFlags", "PInt32", 20, 4, 0x10, 0),
        }),
        new("PTypedObject", "PBase", 8, 4, 0, 0, 0, 0x8, 0, new MemberRow[]
        {
            new("m_object", "PBase", 0, 4, 0x12, 0),
            new("m_classDescriptor", "PClassDescriptor", 4, 4, 0x12, 0),
        }),
        new("PVertexStream", "PBase", 12, 4, 0, 0, 0, 0x0, 0, new MemberRow[]
        {
            new("m_type", "PUInt8", 8, 1, 0x10, 0),
            new("m_offset", "PUInt32", 0, 4, 0x10, 0),
            new("m_renderDataType", "PRenderDataType", 4, 4, 0x12, 0),
            new("m_streamSet", "PUInt8", 9, 1, 0x10, 0),
        }),
        new("PWorldMatrix", "PBase", 48, 4, 0, 0, 0, 0x0, 0, new MemberRow[]
        {
            new("m_matrix", "PMatrix4x3", 0, 48, 0x10, 0),
        }),
        new("Quat", "-", 16, 4, 0, 0, 0, 0x0, 0, new MemberRow[]
        {
            new("m_elements", "float", 0, 4, 0x0, 4),
        }),
        new("Vector3", "-", 16, 4, 0, 0, 0, 0x0, 0, new MemberRow[]
        {
            new("m_elements", "float", 0, 4, 0x0, 4),
        }),
        new("Vector4", "-", 16, 4, 0, 0, 0, 0x0, 0, new MemberRow[]
        {
            new("m_elements", "float", 0, 4, 0x0, 4),
        }),
    };

    private static readonly Dictionary<string, ClassRow> ByName =
        Rows.ToDictionary(row => row.Name, StringComparer.Ordinal);

    /// <summary>The names of every class the library describes.</summary>
    public static IReadOnlyCollection<string> ClassNames => ByName.Keys;

    /// <summary>The primitive type names the corpus uses, for reference.</summary>
    public static IReadOnlyList<string> PrimitiveTypeNames => PrimitiveTypes;

    public static bool Knows(string className) => ByName.ContainsKey(className);

    /// <summary>
    /// Whether the engine treats this class as a header class — the flag that
    /// puts an entry in the header class section and lets its objects be bigger
    /// than the class itself. Only two classes in the game carry it.
    /// </summary>
    public static bool IsHeaderClass(string className)
        => ByName.TryGetValue(className, out var row) && (row.Flags & 4) != 0;

    /// <summary>
    /// Every class this one drags in: the one it derives from, and the class of
    /// each of its members. A cluster that lists a class has to list these too,
    /// since its own descriptors point at them by index.
    /// </summary>
    public static IEnumerable<string> Referenced(string className)
    {
        if (!ByName.TryGetValue(className, out var row)) yield break;
        if (row.SuperClassName != "-") yield return row.SuperClassName;
        foreach (var member in row.Members)
        {
            if (ByName.ContainsKey(member.TypeName)) yield return member.TypeName;
        }
    }

    /// <summary>
    /// Builds the class table a cluster would carry, for the types and classes it
    /// lists and in the order it lists them. Order is the caller's to choose: the
    /// descriptors keep it, while the packed namespace stores the names sorted.
    /// </summary>
    public static PhyreClassDescriptor[] Descriptors(
        IReadOnlyList<string> typeNames,
        IReadOnlyList<string> classNames)
    {
        ArgumentNullException.ThrowIfNull(typeNames);
        ArgumentNullException.ThrowIfNull(classNames);

        var typeIds = new Dictionary<string, uint>(StringComparer.Ordinal);
        for (var index = 0; index < typeNames.Count; index++) typeIds[typeNames[index]] = (uint)index;
        var classIds = new Dictionary<string, uint>(StringComparer.Ordinal);
        for (var index = 0; index < classNames.Count; index++) classIds[classNames[index]] = (uint)index;

        var descriptors = new PhyreClassDescriptor[classNames.Count];
        var memberIndex = 0;
        for (var index = 0; index < classNames.Count; index++)
        {
            if (!ByName.TryGetValue(classNames[index], out var row))
            {
                throw new InvalidOperationException(
                    $"The schema library does not describe '{classNames[index]}'.");
            }

            var members = new PhyreDataMember[row.Members.Length];
            for (var member = 0; member < members.Length; member++, memberIndex++)
            {
                var source = row.Members[member];
                members[member] = new PhyreDataMember(
                    memberIndex,
                    member,
                    source.Name,
                    TypeId(source.TypeName, typeIds, classIds, typeNames.Count),
                    source.TypeName,
                    source.ValueOffset,
                    source.Size,
                    source.Flags,
                    source.FixedArraySize);
            }

            descriptors[index] = new PhyreClassDescriptor(
                index,
                row.Name,
                SuperClassId(row.SuperClassName, classIds),
                row.Size,
                row.Alignment,
                (uint)members.Length,
                row.OffsetFromParent,
                row.OffsetToBase,
                row.OffsetToBaseInAllocatedBlock,
                row.Flags,
                row.DefaultBufferOffset,
                members);
        }
        return descriptors;
    }

    /// <summary>Where a member sits in its class, by name.</summary>
    public static uint MemberOffset(string className, string memberName)
    {
        if (!ByName.TryGetValue(className, out var row))
        {
            throw new InvalidOperationException($"The schema library does not describe '{className}'.");
        }
        foreach (var member in row.Members)
        {
            if (member.Name == memberName) return member.ValueOffset;
        }
        throw new InvalidOperationException($"'{className}' has no member '{memberName}'.");
    }

    /// <summary>How big an instance of a class is.</summary>
    public static uint SizeOf(string className)
        => ByName.TryGetValue(className, out var row)
            ? row.Size
            : throw new InvalidOperationException($"The schema library does not describe '{className}'.");

    private static uint SuperClassId(string name, IReadOnlyDictionary<string, uint> classIds)
    {
        if (name == "-") return 0;
        if (classIds.TryGetValue(name, out var id)) return id + 1;
        throw new InvalidOperationException(
            $"The superclass '{name}' is not among the classes the cluster lists.");
    }

    private static uint TypeId(
        string name,
        IReadOnlyDictionary<string, uint> typeIds,
        IReadOnlyDictionary<string, uint> classIds,
        int typeCount)
    {
        if (typeIds.TryGetValue(name, out var type)) return type;
        if (classIds.TryGetValue(name, out var id)) return (uint)typeCount + 1 + id;
        throw new InvalidOperationException(
            $"The member type '{name}' is neither a type nor a class the cluster lists.");
    }
}
