<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\..\src\ED8Editor.Core\ED8Editor.Core.csproj" />
    <ProjectReference Include="..\..\src\ED8Editor.Assets\ED8Editor.Assets.csproj" />
    <ProjectReference Include="..\..\src\ED8Editor.Ops\ED8Editor.Ops.csproj" />
    <ProjectReference Include="..\..\src\ED8Editor.Packages\ED8Editor.Packages.csproj" />
    <ProjectReference Include="..\..\src\ED8Editor.Phyre\ED8Editor.Phyre.csproj" />
    <ProjectReference Include="..\..\src\ED8Editor.ScriptHeaders\ED8Editor.ScriptHeaders.csproj" />
    <ProjectReference Include="..\..\src\ED8Editor.Application\ED8Editor.Application.csproj" />
    <ProjectReference Include="..\..\src\ED8Editor.Rendering\ED8Editor.Rendering.csproj" />
    <ProjectReference Include="..\..\src\ED8Editor.Scene\ED8Editor.Scene.csproj" />
    <ProjectReference Include="..\..\src\ED8Editor.Tables\ED8Editor.Tables.csproj" />
    <ProjectReference Include="..\..\src\ED8Editor.Decompiler\ED8Editor.Decompiler.csproj" />
  </ItemGroup>
</Project>
