&[
    ("ActiveVoiceTableData", &[
        ("unknown_short_1", Type::U16),
        ("unknown_string_1", Type::CUtf8),
        ("unknown_data_1", Type::X(4)),
        ("unknown_string_2", Type::CUtf8),
        ("unknown_float_1", Type::F32),
        ("unknown_float_2", Type::F32),
        ("unknown_data", Type::X(12)),
    ]),
    ("AttachTableData", &[
        ("character", Type::U16),
        ("unknown_data", Type::X(20)),
        ("model", Type::CUtf8),
        ("attach_point", Type::CUtf8),
    ]),
    ("BaseList", &[
        ("character", Type::I16),
        ("lines", Type::U16),
        ("elements", Type::Repeat(8, Box::new(Type::U16))),
    ]),
    ("OrbLineList", &[
        ("character", Type::I16),
        ("line", Type::U16),
        ("slot_ids", Type::Repeat(8, Box::new(Type::I16))),
    ]),
    ("bgm", &[
        ("id", Type::U16),
        ("track", Type::CUtf8),
        ("unknown_data", Type::X(2)),
    ]),
    ("CardTableData", &[
        ("id", Type::I16),
        ("unknown_string", Type::CUtf8),
        ("unknown_data", Type::X(26)),
    ]),
    ("char_revise", &[
        ("char", Type::CUtf8),
        ("unknown_short_1", Type::U16),
        ("unknown_short_2", Type::U16),
        ("unknown_short_3", Type::U16),
        ("unknown_short_4", Type::U16),
        ("unknown_short_5", Type::U16),
        ("unknown_short_6", Type::U16),
    ]),
    ("dlc", &[
        ("id", Type::I16),
        ("unknown_text_1", Type::CUtf8),
        ("unknown_text_2", Type::CUtf8),
        ("name", Type::CUtf8),
        ("description", Type::CUtf8),
    ]),
    ("FaceSupplementTableData", &[
        ("character", Type::I16),
        ("unknown_data_1", Type::X(16)),
        ("uknown_string", Type::CUtf8),
        ("unknown_data_2", Type::X(8)),
    ]),
    ("FootStepData", &[
        ("unknown_text", Type::CUtf8),
        ("unknown_byte", Type::U8),
    ]),
    ("growth", &[
        ("character", Type::I16),
        ("unknown_short_0", Type::I16),
        ("hp_base", Type::I16),
        ("hp_growth", Type::F32),
        ("str_base", Type::I16),
        ("str_growth", Type::F32),
        ("def_base", Type::I16),
        ("def_growth", Type::F32),
        ("ats_base", Type::I16),
        ("ats_growth", Type::F32),
        ("adf_base", Type::I16),
        ("adf_growth", Type::F32),
        ("spd_base", Type::I16),
        ("spd_growth", Type::F32),
        ("dex_base", Type::I16),
        ("dex_growth", Type::F32),
        ("agl_base", Type::I16),
        ("agl_growth", Type::F32),
        ("mov_base", Type::I16),
        ("mov_growth", Type::F32),
    ]),
    ("hkitugi_lst", &[
        ("unknown_short", Type::U16),
        ("unknown_byte_1", Type::U8),
        ("unknown_byte_2", Type::U8),
        ("cost", Type::U8),
        ("unknown_byte_3", Type::U8),
        ("text", Type::CUtf8),
        ("description", Type::CUtf8),
    ]),
    ("item", &[
        ("id", Type::U16),
        ("character_restriction", Type::U16),
        ("flags", Type::CUtf8),
        ("type", Type::U8),
        ("element", Type::U8),
        ("subtype", Type::U8), // target type for weapons, quartz type (normal/debuff/status quartz) for quartzes
        ("range", Type::U8),
        ("area", Type::U8),
        ("effects", Type::Repeat(2, Box::new(Type::Ref(Header::new("effect").unwrap())))),
        ("str", Type::I16),
        ("def", Type::I16),
        ("ats", Type::I16),
        ("adf", Type::I16),
        ("acc", Type::I16),
        ("eva", Type::I16),
        ("spd", Type::I16),
        ("mov", Type::I16),
        ("hp", Type::I16),
        ("ep", Type::I16),
        ("price", Type::U32),
        ("carry_limit", Type::U8),
        ("sort_id", Type::U8),
        ("unknown_byte_1", Type::U8),
        ("unknown_byte_2", Type::U8),
        ("unknown_byte_3", Type::U8),
        ("unknown_short", Type::I16),
        ("name", Type::CUtf8),
        ("description", Type::CUtf8),
    ]),
    ("LinkAbList", &[
        ("unknown_data", Type::X(5)),
        ("name", Type::CUtf8),
        ("description", Type::CUtf8),
    ]),
    ("LinkLevelExp", &[
        ("level", Type::I8),
        ("exp", Type::I32),
    ]),
    ("MG02Text", &[
        ("character", Type::I16),
        ("id", Type::U16),
        ("unknown_short", Type::U16),
        ("text", Type::CUtf8),
        ("unknown_data", Type::X(6)),
    ]),
    ("magic", &[
        ("id", Type::U16),
        ("character_restriction", Type::U16),
        ("flags", Type::CUtf8),
        ("category", Type::U8),
        ("type", Type::U8),
        ("element", Type::U8),
        ("target_type", Type::U8),
        ("target_range", Type::U8),
        ("target_size", Type::U8),
        ("effects", Type::Repeat(2, Box::new(Type::Ref(Header::new("effect").unwrap())))),
        ("cast_delay", Type::U8),
        ("recovery_delay", Type::U8),
        ("cost", Type::U16),
        ("unbalance_bonus", Type::I8),
        ("level_learn", Type::I8),
        ("sort_id", Type::U16),
        ("animation", Type::CUtf8),
        ("name", Type::CUtf8),
        ("description", Type::CUtf8),
    ]),
    ("MapJumpData", &[
        ("unknown_data_1", Type::X(4)),
        ("name", Type::CUtf8),
        ("unknown_data_2", Type::X(4)),
        ("unknown_string_1", Type::CUtf8),
        ("unknown_string_2", Type::CUtf8),
        ("unknown_data_3", Type::X(28)),
    ]),
    ("MasterQuartzBase", &[
        ("id", Type::I16),
        ("unknown_byte_1", Type::U8),
        ("unknown_byte_2", Type::U8),
        ("unknown_byte_3", Type::U8),
        ("unknown_byte_4", Type::U8),
    ]),
    ("MasterQuartzData", &[
        ("id", Type::I16),
        ("level", Type::U16),
        ("hp", Type::I16),
        ("ep", Type::I16),
        ("str", Type::I16),
        ("def", Type::I16),
        ("ats", Type::I16),
        ("adf", Type::I16),
        ("spd", Type::I16),
        ("effect_data", Type::Repeat(6, Box::new(Type::F32))),
        ("arts", Type::Repeat(2, Box::new(Type::I16))),
        ("memos", Type::Repeat(9, Box::new(Type::I16))),
    ]),
    ("MasterQuartzMemo", &[
        ("item_id", Type::I16),
        ("memo_id", Type::I16),
        ("text", Type::CUtf8),
    ]),
    ("NameTableData", &[
        ("character", Type::U16),
        ("name", Type::CUtf8),
        ("unknown_string_1", Type::CUtf8),
        ("unknown_string_2", Type::CUtf8),
        ("unknown_string_3", Type::CUtf8),
        ("unknown_string_4", Type::CUtf8),
        ("unknown_string_5", Type::CUtf8),
    ]),
    ("NaviTextData", &[
        ("unknown_short", Type::U16),
        ("text", Type::CUtf8),
        ("unknown_data_2", Type::X(4)),
    ]),
    ("PlaceTableData", &[
        ("unknown_short_1", Type::I16),
        ("unknown_short_2", Type::I16),
        ("map", Type::CUtf8),
        ("name", Type::CUtf8),
        ("unknown_string", Type::CUtf8),
    ]),
    ("QSBook", &[
        ("unknown_short_1", Type::U16),
        ("unknown_short_2", Type::U16),
        ("title", Type::CUtf8),
        ("unknown_text_1", Type::CUtf8),
        ("unknown_text_2", Type::CUtf8),
        ("unknown_data", Type::X(2)),
    ]),
    ("QSChapter", &[
        ("id", Type::I16),
        ("chapter", Type::CUtf8),
    ]),
    ("QSBookScp", &[
        ("unknown_text", Type::CUtf8),
    ]),
    ("QSChar", &[
        ("character", Type::U16),
        ("unknown_data", Type::X(4)),
        ("name_short", Type::CUtf8),
        ("name_long", Type::CUtf8),
        ("affiliation_short", Type::CUtf8),
        ("note_1", Type::CUtf8),
        ("note_2_title", Type::CUtf8),
        ("note_2", Type::CUtf8),
        ("note_3_title", Type::CUtf8),
        ("note_3", Type::CUtf8),
        ("note_4_title", Type::CUtf8),
        ("note_4", Type::CUtf8),
    ]),
    ("QSCook", &[
        ("regular_name", Type::CUtf8),
        ("unknown_data_1", Type::X(34)),
        ("superb", Type::Ref(Header::new("QSCookVariantDescription").unwrap())),
        ("regular", Type::Ref(Header::new("QSCookVariantDescription").unwrap())),
        ("peculiar", Type::Ref(Header::new("QSCookVariantDescription").unwrap())),
        ("unique", Type::Ref(Header::new("QSCookVariantDescription").unwrap())),
        ("unknown_data_2", Type::X(11)),
    ]),
    ("QSFish", &[
        ("id", Type::U16),
        ("name", Type::CUtf8),
        ("unknown_data_1", Type::X(96)),
        ("description", Type::CUtf8),
        ("unknown_data_2", Type::X(62)),
    ]),
    ("QSHelp", &[
        ("unknown_short_1", Type::U16),
        ("unknown_short_2", Type::U16),
        ("text", Type::CUtf8),
    ]),
    ("QSMons", &[
        ("enemy", Type::CUtf8),
        ("unknown_short_1", Type::I16),
        ("unknown_short_2", Type::I16),
    ]),
    ("QSRank", &[
        ("id", Type::U16),
        ("text", Type::CUtf8),
        ("unknown_int1", Type::U16),
        ("unknown_int2", Type::U16),
        ("unknown_int3", Type::U16),
    ]),
    ("QSText", &[
        ("id", Type::U16),
        ("unknown_byte_1", Type::U8),
        ("text", Type::CUtf8),
        ("unknown_byte_2", Type::U8),
    ]),
    ("QSTitle", &[
        ("unknown_short", Type::I16),
        ("unknown_byte", Type::U8),
        ("title", Type::CUtf8),
        ("persons", Type::CUtf8),
        ("unknown_data", Type::X(9)),
    ]),
    ("QuartzCost", &[
        ("id", Type::I16),
        ("earth_sepith_cost", Type::U16),
        ("water_sepith_cost", Type::U16),
        ("fire_sepith_cost", Type::U16),
        ("wind_sepith_cost", Type::U16),
        ("time_sepith_cost", Type::U16),
        ("space_sepith_cost", Type::U16),
        ("mirage_sepith_cost", Type::U16),
    ]),
    ("ShopTitle", &[
        ("unknown_short", Type::I16),
        ("unknown_byte", Type::U8),
        ("name", Type::CUtf8),
        ("unknown_data", Type::X(8)),
    ]),
    ("SlotCost", &[
        ("slot_position", Type::I16),
        ("earth_sepith_cost", Type::U16),
        ("water_sepith_cost", Type::U16),
        ("fire_sepith_cost", Type::U16),
        ("wind_sepith_cost", Type::U16),
        ("time_sepith_cost", Type::U16),
        ("space_sepith_cost", Type::U16),
        ("mirage_sepith_cost", Type::U16),
    ]),
    ("SlotEp", &[
        ("character", Type::I16),
        ("ep_base", Type::U16),
        ("ep_increase", Type::Repeat(8, Box::new(Type::I16))),
    ]),
    ("status", &[
        ("script", Type::CUtf8),
        ("texture", Type::CUtf8),
        ("model", Type::CUtf8),
        ("model_scale", Type::F32),
        ("camera_height", Type::F32),
        ("hitbox_size", Type::F32),
        ("unknown_data_1", Type::X(4)),
        ("unknown_float_4", Type::F32),
        ("unknown_short_1", Type::U16),
        ("unknown_short_2", Type::U16),
        ("is_female", Type::U8),
        ("level", Type::U8),
        ("hp", Type::U32),
        ("hp_start", Type::U32),
        ("ep", Type::U16),
        ("ep_start", Type::U16),
        ("cp", Type::U16),
        ("cp_start", Type::U16),
        ("str", Type::U16),
        ("def", Type::U16),
        ("ats", Type::U16),
        ("adf", Type::U16),
        ("unknown_short_7", Type::U16),
        ("unknown_short_8", Type::U16),
        ("spd", Type::U16),
        ("unknown_short_10", Type::U16),
        ("exp", Type::U16),
        ("earth_efficacy", Type::U8),
        ("water_efficacy", Type::U8),
        ("fire_efficacy", Type::U8),
        ("wind_efficacy", Type::U8),
        ("time_efficacy", Type::U8),
        ("space_efficacy", Type::U8),
        ("mirage_efficacy", Type::U8),
        ("psn_efficacy", Type::U8),
        ("seal_efficacy", Type::U8),
        ("mute_efficacy", Type::U8),
        ("blnd_efficacy", Type::U8),
        ("slp_efficacy", Type::U8),
        ("burn_efficacy", Type::U8),
        ("frz_efficacy", Type::U8),
        ("petr_efficacy", Type::U8),
        ("fnt_efficacy", Type::U8),
        ("conf_efficacy", Type::U8),
        ("dblw_efficacy", Type::U8),
        ("nmr_efficacy", Type::U8),
        ("dlay_efficacy", Type::U8),
        ("vnsh_efficacy", Type::U8),
        ("s_down_efficacy", Type::U8),
        ("slash_efficacy", Type::U16),
        ("thrust_efficacy", Type::U16),
        ("pierce_efficacy", Type::U16),
        ("strike_efficacy", Type::U16),
        ("earth_sepith", Type::U8),
        ("water_sepith", Type::U8),
        ("fire_sepith", Type::U8),
        ("wind_sepith", Type::U8),
        ("time_sepith", Type::U8),
        ("space_sepith", Type::U8),
        ("mirage_sepith", Type::U8),
        ("sepith_mass", Type::U8),
        ("drop_1_id", Type::I16),
        ("drop_1_chance", Type::U8),
        ("drop_2_id", Type::I16),
        ("drop_2_chance", Type::U8),
        ("monster_variation_min", Type::F32),
        ("monster_variation_max", Type::F32),
        ("flags", Type::CUtf8),
        ("name", Type::CUtf8),
        ("description", Type::CUtf8),
    ]),
    ("status_revise", &[
        ("difficulty", Type::U16),
        ("unknown_short_1", Type::U16),
        ("unknown_short_2", Type::U16),
        ("unknown_short_3", Type::U16),
        ("unknown_short_4", Type::U16),
        ("unknown_short_5", Type::U16),
        ("unknown_short_6", Type::U16),
    ]),
    ("TacticalBonus", &[
        ("id", Type::U16),
        ("name", Type::CUtf8),
        ("bonus", Type::F32),
        ("unknown_data", Type::X(2)),
    ]),
    ("TextTableData", &[
        ("id", Type::U16),
        ("text", Type::CUtf8),
    ]),
    ("text_lst", &[
        ("id", Type::U16),
        ("text", Type::CUtf8),
    ]),
    ("voice", &[
        ("id", Type::U16),
        ("unknown_byte", Type::U8),
        ("clip", Type::CUtf8),
        ("unknown_short", Type::U16),
        ("unknown_float", Type::F32),
        ("unknown_data", Type::X(8)),
    ]),
    ("weapon_attribute", &[
        ("character", Type::I16),
        ("unknown_byte_1", Type::U8),
        ("unknown_byte_2", Type::U8),
        ("unknown_byte_3", Type::U8),
        ("unknown_byte_4", Type::U8),
        ("unknown_float_1", Type::F32),
        ("unknown_float_2", Type::F32),
        ("unknown_float_3", Type::F32),
    ]),
]