using System.Text;

namespace ED8Editor.Shaders.Investigation;

/// <summary>
/// Merges all permutations of a Phyre shader into a single, unified HLSL
/// source file. Context switches become #define macros at the top, and
/// the disassembly from each permutation is included in #if blocks.
///
/// This is useful for understanding what the complete shader looks like
/// and for creating a base shader that can be edited and re-compiled.
/// </summary>
public sealed class PhyreShaderMerger
{
    /// <summary>
    /// Merges all shader stages from an fx.phyre into a single HLSL file.
    /// </summary>
    public string Merge(PhyreShaderSource source, MergeOptions? options = null)
    {
        options ??= new MergeOptions();
        var sb = new StringBuilder();

        // Header
        sb.AppendLine("// ============================================================");
        sb.AppendLine("// Merged Phyre Shader");
        sb.AppendLine("// Generated by ED8Editor.Shaders");
        sb.AppendLine("//");
        sb.AppendLine($"// Context switches: {string.Join(", ", source.ContextSwitchNames)}");
        sb.AppendLine($"// Context variants: {source.Contexts.Count}");
        sb.AppendLine($"// Render passes: {string.Join(", ", source.Stages.Select(s => s.PassName).Distinct())}");
        sb.AppendLine($"// Total permutations: {source.Stages.Count}");
        sb.AppendLine("// ============================================================");
        sb.AppendLine();

        // Material switches as comments
        if (source.MaterialSwitches.Count > 0)
        {
            sb.AppendLine("// Material switches:");
            foreach (var (key, value) in source.MaterialSwitches)
                sb.AppendLine($"//   {key} = {value}");
            sb.AppendLine();
        }

        // Context switch definitions
        sb.AppendLine("// === Context Switch Definitions ===");
        sb.AppendLine("// These are the switches the engine uses to select a permutation.");
        sb.AppendLine("// Each switch is a preprocessor macro that can be #define'd.");
        sb.AppendLine();
        foreach (var switchName in source.ContextSwitchNames)
        {
            var values = source.Contexts
                .Where(c => c.PackedValues.TryGetValue(switchName, out _))
                .Select(c => c.PackedValues[switchName])
                .Distinct()
                .ToArray();

            sb.AppendLine($"// {switchName}: possible values = {{{string.Join(", ", values)}}}");
        }
        sb.AppendLine();

        // Group stages by pass name
        var passGroups = source.Stages
            .GroupBy(s => s.PassName)
            .ToDictionary(g => g.Key, g => g.ToArray());

        foreach (var (passName, stages) in passGroups)
        {
            sb.AppendLine($"// ============================================================");
            sb.AppendLine($"// RENDER PASS: {passName}");
            sb.AppendLine($"// Permutations: {stages.Length}");
            sb.AppendLine($"// ============================================================");
            sb.AppendLine();

            for (var i = 0; i < stages.Length; i++)
            {
                var stage = stages[i];
                WritePermutationBlock(sb, stage, i, options);
                sb.AppendLine();
            }
        }

        // Summary section
        if (options.IncludeSummary)
        {
            sb.AppendLine("// ============================================================");
            sb.AppendLine("// STRUCTURE SUMMARY");
            sb.AppendLine("// ============================================================");
            sb.AppendLine();

            WriteStructureSummary(sb, source);
        }

        return sb.ToString();
    }

    /// <summary>
    /// Attempts to reconstruct HLSL source by merging the disassembly of
    /// all permutations and identifying common patterns. This is heuristic
    /// and may not produce perfect HLSL, but gives a good starting point.
    /// </summary>
    public string ReconstructHlsl(PhyreShaderSource source)
    {
        var sb = new StringBuilder();

        sb.AppendLine("// ============================================================");
        sb.AppendLine("// Reconstructed HLSL Shader");
        sb.AppendLine("// This is a heuristic reconstruction - verify before compiling.");
        sb.AppendLine("// ============================================================");
        sb.AppendLine();

        // Context switches as defines
        foreach (var switchName in source.ContextSwitchNames)
        {
            sb.AppendLine($"#ifndef {switchName}");
            sb.AppendLine($"#define {switchName} 0");
            sb.AppendLine("#endif");
        }
        sb.AppendLine();

        // Input structure from first VS
        if (source.Stages.Count > 0)
        {
            var firstStage = source.Stages[0];
            sb.AppendLine("// === Vertex Input ===");
            sb.AppendLine("struct VertexInput");
            sb.AppendLine("{");
            foreach (var input in firstStage.Inputs)
            {
                sb.AppendLine($"    // {input.Name}_{input.SemanticIndex}: RenderType={input.RenderType}, DataType={input.DataType}");
            }
            sb.AppendLine("    float3 Position : POSITION;");
            sb.AppendLine("    float3 Normal : NORMAL;");
            sb.AppendLine("    float2 TexCoord : TEXCOORD0;");
            sb.AppendLine("};");
            sb.AppendLine();

            // Phyre reserved constant buffer
            sb.AppendLine("// === Phyre Global Constant Buffer (b0) ===");
            sb.AppendLine("cbuffer PhyreGlobals : register(b0)");
            sb.AppendLine("{");
            sb.AppendLine("    float4 _phyreReserved[29];  // Engine-reserved slots");
            sb.AppendLine("    float4x4 WorldViewProjection;  // Required: at offset 29*16 = 464");
            sb.AppendLine("    // ... additional engine parameters follow ...");
            sb.AppendLine("};");
            sb.AppendLine();

            // Each permutation's disassembly as a comment block
            sb.AppendLine("// === Permutation Disassembly (for reference) ===");
            sb.AppendLine();

            var passGroups = source.Stages
                .GroupBy(s => s.PassName)
                .ToDictionary(g => g.Key, g => g.ToArray());

            foreach (var (passName, stages) in passGroups)
            {
                for (var i = 0; i < stages.Length; i++)
                {
                    var stage = stages[i];
                    sb.AppendLine($"// --- {passName} permutation {i}: {stage.ContextLabel} ---");
                    sb.AppendLine($"// VS constant buffer: {stage.VertexConstantBufferSize} bytes");
                    sb.AppendLine($"// PS constant buffer: {stage.FragmentConstantBufferSize} bytes");
                    sb.AppendLine();

                    sb.AppendLine("/* Vertex Shader disassembly:");
                    foreach (var line in stage.VertexShaderDisassembly.Split('\n'))
                        sb.AppendLine($"//   {line.TrimEnd()}");
                    sb.AppendLine("*/");
                    sb.AppendLine();

                    sb.AppendLine("/* Fragment Shader disassembly:");
                    foreach (var line in stage.FragmentShaderDisassembly.Split('\n'))
                        sb.AppendLine($"//   {line.TrimEnd()}");
                    sb.AppendLine("*/");
                    sb.AppendLine();
                }
            }
        }

        return sb.ToString();
    }

    private static void WritePermutationBlock(
        StringBuilder sb, DecompiledStage stage, int index, MergeOptions options)
    {
        sb.AppendLine($"// --- Permutation {index}: {stage.ContextLabel} ---");
        sb.AppendLine($"// VS CB size: {stage.VertexConstantBufferSize} bytes");
        sb.AppendLine($"// PS CB size: {stage.FragmentConstantBufferSize} bytes");
        sb.AppendLine();

        if (options.IncludeDisassembly)
        {
            sb.AppendLine("// === Vertex Shader ===");
            sb.AppendLine(stage.VertexShaderDisassembly);
            sb.AppendLine();

            sb.AppendLine("// === Fragment Shader ===");
            sb.AppendLine(stage.FragmentShaderDisassembly);
            sb.AppendLine();
        }
    }

    private static void WriteStructureSummary(StringBuilder sb, PhyreShaderSource source)
    {
        sb.AppendLine("// Input semantics by pass:");
        foreach (var passGroup in source.Stages.GroupBy(s => s.PassName))
        {
            sb.AppendLine($"//   {passGroup.Key}:");
            var semantics = passGroup
                .SelectMany(s => s.Inputs)
                .Select(si => $"{si.Name}_{si.SemanticIndex}")
                .Distinct();
            foreach (var sem in semantics)
                sb.AppendLine($"//     - {sem}");
        }
        sb.AppendLine();

        sb.AppendLine("// Context variant matrix:");
        sb.AppendLine($"//   Switches: {string.Join(" | ", source.ContextSwitchNames)}");
        foreach (var ctx in source.Contexts)
        {
            var values = string.Join(" | ",
                source.ContextSwitchNames.Select(n =>
                    ctx.PackedValues.TryGetValue(n, out var v) ? v.ToString() : "-"));
            sb.AppendLine($"//   Variant {ctx.VariantIndex}: {values}");
        }
    }
}

/// <summary>
/// Options for the shader merge operation.
/// </summary>
public sealed record MergeOptions(
    bool IncludeDisassembly = true,
    bool IncludeSummary = true);
