// cs1_script_parser.h -- parseur du bytecode de script CS1 (Trails of Cold Steel)
// Structures extraites du desassemblage Ghidra, validees sur 321 scripts reels.
// Taux de parsing bout-en-bout : ~89.6%% des fonctions (JP et US quasi identiques -> parseur agnostique au contenu).
// Code (fonctions nommees) uniquement : ~89.6%%. Les entrees sans nom sont des tables de donnees (accedees par index, pas du code).
#pragma once
#include <cstdint>
#include <cstddef>
#include <cstring>
namespace cs1 {

enum OperandType : uint16_t { OPD_END=0,OPD_U8,OPD_U16,OPD_U32,OPD_I32,OPD_EXPR,OPD_CSTR,OPD_DIALOG,OPD_SWITCH,OPD_UNKNOWN,OPD_SPECIAL,OPD_FIX_BASE=0x100 };
#define OPD_FIX(n) ((cs1::OperandType)(cs1::OPD_FIX_BASE | (n)))
struct OpInfo { const char* name; const char* category; OperandType operands[48]; uint8_t confidence; };
static const OpInfo OPCODES[160] = {
  /*  0*/ { "YIELD","flow", {OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END}, 2 },
  /*  1*/ { "RETURN","flow", {OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END}, 2 },
  /*  2*/ { "CALL","flow", {OPD_U8,OPD_CSTR,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END}, 2 },
  /*  3*/ { "JMP","flow", {OPD_U32,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END}, 2 },
  /*  4*/ { "CALL_EXT","flow", {OPD_U8,OPD_CSTR,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END}, 2 },
  /*  5*/ { "JMP_IF_FALSE","flow", {OPD_EXPR,OPD_U32,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END}, 2 },
  /*  6*/ { "SWITCH","flow", {OPD_EXPR,OPD_SWITCH,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END}, 2 },
  /*  7*/ { "LOAD_ACC","reg", {OPD_U32,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END}, 2 },
  /*  8*/ { "SET_SYS","state", {OPD_U8,OPD_EXPR,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END}, 2 },
  /*  9*/ { "NOP","flow", {OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END}, 2 },
  /* 10*/ { "SET_REG","reg", {OPD_U8,OPD_EXPR,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END}, 2 },
  /* 11*/ { "NOP","flow", {OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END}, 2 },
  /* 12*/ { "SET_FLAG","state", {OPD_U16,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END}, 2 },
  /* 13*/ { "RESET_FLAG","state", {OPD_U16,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END}, 2 },
  /* 14*/ { "SET_FLAGS_MASK","state", {OPD_U32,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END}, 2 },
  /* 15*/ { "CLR_FLAGS_MASK?","state", {OPD_U32,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END}, 2 },
  /* 16*/ { "OP16","?", {OPD_U16,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END}, 2 },
  /* 17*/ { "OP17","?", {OPD_U16,OPD_U16,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END}, 2 },
  /* 18*/ { "SET_REG2","reg", {OPD_U8,OPD_EXPR,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END}, 2 },
  /* 19*/ { "OP19","?", {OPD_SPECIAL,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END}, 1 },
  /* 20*/ { "OP20","?", {OPD_U16,OPD_U8,OPD_U8,OPD_CSTR,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END}, 1 },
  /* 21*/ { "OP21","?", {OPD_FIX(3),OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END}, 2 },
  /* 22*/ { "OP22","?", {OPD_U8,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END}, 1 },
  /* 23*/ { "OP23","?", {OPD_U8,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END}, 1 },
  /* 24*/ { "OP24","?", {OPD_U16,OPD_DIALOG,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END}, 2 },
  /* 25*/ { "OP25","?", {OPD_SPECIAL,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END}, 2 },
  /* 26*/ { "OP26","?", {OPD_U16,OPD_DIALOG,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END}, 2 },
  /* 27*/ { "OP27","?", {OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END}, 2 },
  /* 28*/ { "OP28","?", {OPD_FIX(0),OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END}, 1 },
  /* 29*/ { "OP29","?", {OPD_CSTR,OPD_U16,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END}, 2 },
  /* 30*/ { "OP30","?", {OPD_CSTR,OPD_CSTR,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END}, 2 },
  /* 31*/ { "OP31","?", {OPD_SPECIAL,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END}, 1 },
  /* 32*/ { "OP32","?", {OPD_SPECIAL,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END}, 1 },
  /* 33*/ { "OP33","?", {OPD_SPECIAL,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END}, 2 },
  /* 34*/ { "OP34","?", {OPD_FIX(2),OPD_CSTR,OPD_FIX(21),OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END}, 1 },
  /* 35*/ { "OP35","?", {OPD_FIX(6),OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END}, 2 },
  /* 36*/ { "OP36","?", {OPD_U8,OPD_U16,OPD_CSTR,OPD_CSTR,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END}, 1 },
  /* 37*/ { "OP37","?", {OPD_U8,OPD_U16,OPD_CSTR,OPD_CSTR,OPD_U32,OPD_U32,OPD_U32,OPD_U32,OPD_U32,OPD_U32,OPD_U32,OPD_U32,OPD_U32,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END}, 1 },
  /* 38*/ { "OP38","?", {OPD_U8,OPD_CSTR,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END}, 1 },
  /* 39*/ { "OP39","?", {OPD_SPECIAL,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END}, 1 },
  /* 40*/ { "OP40","?", {OPD_SPECIAL,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END}, 1 },
  /* 41*/ { "OP41","?", {OPD_FIX(17),OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END}, 2 },
  /* 42*/ { "OP42","?", {OPD_U16,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END}, 2 },
  /* 43*/ { "OP43","?", {OPD_FIX(6),OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END}, 2 },
  /* 44*/ { "OP44","?", {OPD_FIX(6),OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END}, 2 },
  /* 45*/ { "OP45","?", {OPD_SPECIAL,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END}, 1 },
  /* 46*/ { "OP46","?", {OPD_FIX(18),OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END}, 2 },
  /* 47*/ { "OP47","?", {OPD_U16,OPD_U8,OPD_CSTR,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END}, 1 },
  /* 48*/ { "OP48","?", {OPD_SPECIAL,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END}, 1 },
  /* 49*/ { "OP49","?", {OPD_SPECIAL,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END}, 1 },
  /* 50*/ { "OP50","?", {OPD_SPECIAL,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END}, 1 },
  /* 51*/ { "OP51","?", {OPD_FIX(11),OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END}, 2 },
  /* 52*/ { "OP52","?", {OPD_FIX(9),OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END}, 2 },
  /* 53*/ { "OP53","?", {OPD_U16,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END}, 2 },
  /* 54*/ { "OP54","?", {OPD_SPECIAL,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END}, 2 },
  /* 55*/ { "OP55","?", {OPD_SPECIAL,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END}, 1 },
  /* 56*/ { "OP56","?", {OPD_FIX(22),OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END}, 2 },
  /* 57*/ { "OP57","?", {OPD_SPECIAL,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END}, 1 },
  /* 58*/ { "OP58","?", {OPD_FIX(9),OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END}, 2 },
  /* 59*/ { "OP59","?", {OPD_FIX(18),OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END}, 2 },
  /* 60*/ { "OP60","?", {OPD_SPECIAL,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END}, 1 },
  /* 61*/ { "OP61","?", {OPD_FIX(1),OPD_CSTR,OPD_FIX(2),OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END}, 1 },
  /* 62*/ { "OP62","?", {OPD_FIX(7),OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END}, 2 },
  /* 63*/ { "OP63","?", {OPD_SPECIAL,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END}, 2 },
  /* 64*/ { "OP64","?", {OPD_FIX(19),OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END}, 2 },
  /* 65*/ { "OP65","?", {OPD_FIX(21),OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END}, 2 },
  /* 66*/ { "OP66","?", {OPD_FIX(3),OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END}, 1 },
  /* 67*/ { "OP67","?", {OPD_U32,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END}, 2 },
  /* 68*/ { "OP68","?", {OPD_SPECIAL,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END}, 2 },
  /* 69*/ { "OP69","?", {OPD_CSTR,OPD_CSTR,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END}, 1 },
  /* 70*/ { "OP70","?", {OPD_FIX(22),OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END}, 2 },
  /* 71*/ { "OP71","?", {OPD_FIX(3),OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END}, 2 },
  /* 72*/ { "OP72","?", {OPD_SPECIAL,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END}, 1 },
  /* 73*/ { "OP73","?", {OPD_SPECIAL,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END}, 1 },
  /* 74*/ { "OP74","?", {OPD_FIX(38),OPD_CSTR,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END}, 2 },
  /* 75*/ { "OP75","?", {OPD_SPECIAL,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END}, 2 },
  /* 76*/ { "OP76","?", {OPD_U16,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END}, 2 },
  /* 77*/ { "OP77","?", {OPD_U8,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END}, 2 },
  /* 78*/ { "OP78","?", {OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END}, 2 },
  /* 79*/ { "OP79","?", {OPD_U16,OPD_U16,OPD_CSTR,OPD_U8,OPD_U16,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END}, 1 },
  /* 80*/ { "OP80","?", {OPD_U16,OPD_U8,OPD_EXPR,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END}, 1 },
  /* 81*/ { "OP81","?", {OPD_FIX(3),OPD_CSTR,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END}, 1 },
  /* 82*/ { "OP82","?", {OPD_FIX(2),OPD_CSTR,OPD_FIX(36),OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END}, 1 },
  /* 83*/ { "OP83","?", {OPD_FIX(9),OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END}, 2 },
  /* 84*/ { "OP84","?", {OPD_FIX(4),OPD_CSTR,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END}, 1 },
  /* 85*/ { "OP85","?", {OPD_U16,OPD_U8,OPD_CSTR,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END}, 2 },
  /* 86*/ { "OP86","?", {OPD_CSTR,OPD_U16,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END}, 1 },
  /* 87*/ { "OP87","?", {OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END}, 1 },
  /* 88*/ { "OP88","?", {OPD_U16,OPD_U8,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END}, 1 },
  /* 89*/ { "OP89","?", {OPD_U16,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END}, 2 },
  /* 90*/ { "OP90","?", {OPD_U8,OPD_CSTR,OPD_U16,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END}, 1 },
  /* 91*/ { "OP91","?", {OPD_SPECIAL,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END}, 2 },
  /* 92*/ { "OP92","?", {OPD_SPECIAL,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END}, 2 },
  /* 93*/ { "OP93","?", {OPD_SPECIAL,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END}, 1 },
  /* 94*/ { "OP94","?", {OPD_SPECIAL,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END}, 1 },
  /* 95*/ { "OP95","?", {OPD_SPECIAL,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END}, 2 },
  /* 96*/ { "OP96","?", {OPD_SPECIAL,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END}, 2 },
  /* 97*/ { "OP97","?", {OPD_FIX(6),OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END}, 2 },
  /* 98*/ { "OP98","?", {OPD_CSTR,OPD_U32,OPD_U16,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END}, 1 },
  /* 99*/ { "OP99","?", {OPD_FIX(19),OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END}, 2 },
  /*100*/ { "OP100","?", {OPD_SPECIAL,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END}, 1 },
  /*101*/ { "OP101","?", {OPD_SPECIAL,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END}, 1 },
  /*102*/ { "OP102","?", {OPD_FIX(6),OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END}, 2 },
  /*103*/ { "OP103","?", {OPD_SPECIAL,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END}, 2 },
  /*104*/ { "OP104","?", {OPD_U32,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END}, 2 },
  /*105*/ { "OP105","?", {OPD_SPECIAL,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END}, 1 },
  /*106*/ { "OP106","?", {OPD_SPECIAL,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END}, 1 },
  /*107*/ { "OP107","?", {OPD_FIX(2),OPD_CSTR,OPD_CSTR,OPD_FIX(1),OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END}, 1 },
  /*108*/ { "OP108","?", {OPD_U16,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END}, 2 },
  /*109*/ { "OP109","?", {OPD_U8,OPD_CSTR,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END}, 1 },
  /*110*/ { "OP110","?", {OPD_SPECIAL,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END}, 2 },
  /*111*/ { "OP111","?", {OPD_SPECIAL,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END}, 1 },
  /*112*/ { "OP112","?", {OPD_SPECIAL,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END}, 1 },
  /*113*/ { "OP113","?", {OPD_SPECIAL,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END}, 1 },
  /*114*/ { "OP114","?", {OPD_U16,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END}, 2 },
  /*115*/ { "OP115","?", {OPD_SPECIAL,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END}, 2 },
  /*116*/ { "OP116","?", {OPD_U8,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END}, 1 },
  /*117*/ { "OP117","?", {OPD_U8,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END}, 2 },
  /*118*/ { "OP118","?", {OPD_SPECIAL,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END}, 1 },
  /*119*/ { "OP119","?", {OPD_FIX(30),OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END}, 2 },
  /*120*/ { "OP120","?", {OPD_FIX(8),OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END}, 2 },
  /*121*/ { "OP121","?", {OPD_SPECIAL,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END}, 2 },
  /*122*/ { "OP122","?", {OPD_U16,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END}, 2 },
  /*123*/ { "OP123","?", {OPD_U8,OPD_U16,OPD_U16,OPD_U16,OPD_U16,OPD_U16,OPD_U32,OPD_U32,OPD_U32,OPD_CSTR,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END}, 1 },
  /*124*/ { "OP124","?", {OPD_U32,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END}, 2 },
  /*125*/ { "OP125","?", {OPD_U32,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END}, 2 },
  /*126*/ { "OP126","?", {OPD_U16,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END}, 2 },
  /*127*/ { "OP127","?", {OPD_SPECIAL,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END}, 1 },
  /*128*/ { "OP128","?", {OPD_FIX(21),OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END}, 2 },
  /*129*/ { "OP129","?", {OPD_SPECIAL,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END}, 2 },
  /*130*/ { "OP130","?", {OPD_FIX(6),OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END}, 2 },
  /*131*/ { "OP131","?", {OPD_FIX(14),OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END}, 2 },
  /*132*/ { "OP132","?", {OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END}, 2 },
  /*133*/ { "OP133","?", {OPD_CSTR,OPD_FIX(4),OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END}, 1 },
  /*134*/ { "OP134","?", {OPD_SPECIAL,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END}, 2 },
  /*135*/ { "OP135","?", {OPD_FIX(3),OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END}, 2 },
  /*136*/ { "OP136","?", {OPD_SPECIAL,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END}, 1 },
  /*137*/ { "OP137","?", {OPD_SPECIAL,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END}, 1 },
  /*138*/ { "OP138","?", {OPD_SPECIAL,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END}, 1 },
  /*139*/ { "OP139","?", {OPD_U16,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END}, 1 },
  /*140*/ { "OP140","?", {OPD_U16,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END}, 2 },
  /*141*/ { "OP141","?", {OPD_FIX(6),OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END}, 2 },
  /*142*/ { "OP142","?", {OPD_U16,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END}, 2 },
  /*143*/ { "OP143","?", {OPD_FIX(14),OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END}, 2 },
  /*144*/ { "OP144","?", {OPD_SPECIAL,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END}, 1 },
  /*145*/ { "OP145","?", {OPD_SPECIAL,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END}, 2 },
  /*146*/ { "OP146","?", {OPD_U16,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END}, 2 },
  /*147*/ { "OP147","?", {OPD_U8,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END}, 1 },
  /*148*/ { "OP148","?", {OPD_FIX(16),OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END}, 2 },
  /*149*/ { "OP149","?", {OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END}, 2 },
  /*150*/ { "OP150","?", {OPD_FIX(16),OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END}, 2 },
  /*151*/ { "OP151","?", {OPD_U16,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END}, 2 },
  /*152*/ { "OP152","?", {OPD_U32,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END}, 2 },
  /*153*/ { "OP153","?", {OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END},  1 },
  /*154*/ { "OP154","?", {OPD_SPECIAL,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END}, 2 },
  /*155*/ { "OP155","?", {OPD_FIX(14),OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END}, 2 },
  /*156*/ { "OP156","?", {OPD_U8,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END}, 2 },
  /*157*/ { "OP157","?", {OPD_U32,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END}, 2 },
  /*158*/ { "OP158","?", {OPD_U8,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END}, 1 },
  /*159*/ { "OP159","?", {OPD_U8,OPD_U16,OPD_U16,OPD_U16,OPD_U16,OPD_U16,OPD_U16,OPD_U16,OPD_U16,OPD_U16,OPD_U16,OPD_U32,OPD_U32,OPD_U32,OPD_U32,OPD_U8,OPD_CSTR,OPD_CSTR,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END,OPD_END}, 1 },
};

static inline int cs1_cstr(const uint8_t*p,size_t m){ size_t i=0; while(i<m&&p[i])i++; return i<m?(int)(i+1):-1; }
static inline int cs1_expr_sz(uint8_t b){ switch(b){case 0:return 5;case 0x1c:return 5;case 0x1e:return 3;case 0x1f:case 0x20:case 0x23:return 2;case 0x21:return 4;default:return 1;} }
static inline int cs1_instr_length(const uint8_t*p,size_t max);
static inline int cs1_expr(const uint8_t*p,size_t m){ size_t i=0; while(i<m){uint8_t b=p[i];
  if(b==1)return(int)(i+1);
  if(b==0x1c){ if(i+1>=m)return -1; int sl=cs1_instr_length(p+i+1,m-(i+1)); if(sl<=0)return -1; i+=1+(size_t)sl; continue; }
  i+=cs1_expr_sz(b);} return -1; }
static inline int cs1_dialog(const uint8_t*p,size_t m){ size_t i=0; while(i<m){uint8_t b=p[i]; if(b==0)return(int)(i+1); if(b<0x20)i+=(b==0x10)?3:((b==0x11||b==0x12)?5:1); else i+=1;} return -1; }
static inline int L60(const uint8_t*p,size_t m){ if(7>m)return -1; int n=7; if((p[3]|(p[4]<<8))==0xFFFF)n+=12; return n; }
static inline int L118(const uint8_t*p,size_t m){ if(2>m)return -1; if(p[1]<=1){int c=cs1_cstr(p+2,m-2);return c<0?-1:2+c+2;} return 2; }
static inline int L57(const uint8_t*p,size_t m){ if(4>m)return -1; uint8_t c=p[1]; int n=4; if(c!=0x0C&&c!=5&&c!=0x69&&c!=0x0A&&c!=0x0B&&c!=0xFF&&c!=0xFE)n+=4; return n; }
static inline int L112(const uint8_t*p,size_t m){ if(2>m)return -1; if(p[1]==1){int c=cs1_cstr(p+2,m-2);return c<0?-1:2+c+3;} return 2; }
static inline int L113(const uint8_t*p,size_t m){ if(2>m)return -1; return p[1]==0?12:2; }
static inline int L137(const uint8_t*p,size_t m){ if(2>m)return -1; return p[1]==0?6:2; }
static inline int L138(const uint8_t*p,size_t m){ if(2>m)return -1; if(p[1]==0){int c1=cs1_cstr(p+2,m-2);if(c1<0)return -1;int c2=cs1_cstr(p+2+c1,m-2-c1);return c2<0?-1:2+c1+c2;} return 2; }
static inline int L31(const uint8_t*p,size_t m){ if(3>m)return -1; uint8_t b1=p[1],b2=p[2]; int n=3; if(b2<4){if(b1==0)n+=6;else if(b1==1){int c=cs1_cstr(p+3,m-3);if(c<0)return -1;n+=c+2;}else if(b1==2)n+=5;else if(b1==4)n+=1;else if(b1==5)n+=4;else if(b1==6||b1==7)n+=2;} return n; }
static inline int L95(const uint8_t*p,size_t m){ if(4>m)return -1; uint8_t t=p[3]; if(t==0||t==3)return 11; if(t==2)return 16; return 4; }
static inline int L63(const uint8_t*p,size_t m){ if(2>m)return -1; uint8_t t=p[1]; if(t==0||t==1||t==4||t==5||t==6||t==9||t==10||t==11)return 4; if(t==8)return 8; return 2; }
static inline int L115(const uint8_t*p,size_t m){ if(2>m)return -1; uint8_t t=p[1]; if(t==0||t==1)return 2; if(t==3)return 14; if(t==5)return 6; return 4; }
static inline int L101(const uint8_t*p,size_t m){ if(2>m)return -1; static const int T[10]={7,5,6,7,5,7,6,5,8,5}; uint8_t t=p[1]; return t<10?T[t]:5; }
static inline int L25(const uint8_t*p,size_t m){ if(2>m)return -1; uint8_t t=p[1]; if(t==0||t==5)return 11; if(t==1)return 7; if(t==2)return 6; return 2; }
static inline int L36(const uint8_t*p,size_t m){ if(2>m)return -1; uint8_t t=p[1]; size_t i=14; switch(t){
case 0:  break;
case 1:  break;
case 2:  break;
case 3:  break;
case 4:  break;
case 5:  break;
case 6:  break;
case 7:  break;
case 8:  break;
case 9:  break;
case 10:  break;
case 11:  break;
default: return 14; } return (int)i; }
static inline int L40(const uint8_t*p,size_t m){ if(2>m)return -1; static const int T[127]={7,12,3,2,3,2,3,2,2,2,2,2,2,2,10,6,4,5,4,20,4,24,2,4,2,4,4,2,4,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,24,2,8,20,12,27,2,2,2,2,14,2,2,2,2,2,2,2,2,2,14,2,4,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,8,7,2,4,4,4,4,9,5,4,2,4,4,2,2,2,2,4,4,4,18,2,2,9,13,4,4,4,2,2,2,4,5,2,2,2,9}; uint8_t t=p[1]; return t<127?T[t]:2; }
static inline int L45(const uint8_t*p,size_t m){ if(2>m)return -1; uint8_t t=p[1]; size_t i=2; switch(t){
case 0:  break;
case 1:  break;
case 2: i+=15; break;
case 3: i+=3;{int c=cs1_cstr(p+i,m-i);if(c<0)return -1;i+=c;}i+=14; break;
case 4: i+=16; break;
case 5: i+=7; break;
case 6:  break;
case 7: i+=2; break;
case 8: i+=3; break;
case 9: i+=12; break;
case 10:  break;
case 11: i+=7; break;
case 12: i+=15; break;
case 13: i+=15; break;
case 14: i+=11; break;
case 15: i+=14; break;
case 16:  break;
case 17: i+=16; break;
case 18: i+=2; break;
case 19: i+=18; break;
case 20: i+=3;{int c=cs1_cstr(p+i,m-i);if(c<0)return -1;i+=c;}i+=14; break;
case 21: i+=10; break;
case 22: i+=7; break;
case 23: i+=2; break;
default: return 2; } return (int)i; }
static inline int L48(const uint8_t*p,size_t m){ if(2>m)return -1; uint8_t t=p[1]; size_t i=2; switch(t){
case 0: i+=13; break;
case 1: i+=3; break;
case 2: i+=1; break;
case 3: i+=7; break;
case 4: i+=13; break;
case 5: i+=4; break;
case 6: i+=2; break;
case 7:  break;
default: return 2; } return (int)i; }
static inline int L145(const uint8_t*p,size_t m){ if(2>m)return -1; return p[1]==0?11:2; }
static inline int L129(const uint8_t*p,size_t m){ if(2>m)return -1; return p[1]==0?4:2; }
static inline int L33(const uint8_t*p,size_t m){ if(2>m)return -1; return p[1]==1?16:8; }
static inline int L49(const uint8_t*p,size_t m){ if(2>m)return -1; uint8_t t=p[1];
  if(t==0||t==0x32){ if(38>m)return -1; int c=cs1_cstr(p+38,m-38); return c<0?-1:38+c; }
  if(t==0xfe)return 4; if(t>=0xff)return 14; if(t==0xfd)return 3;
  switch(t){ case 1: case 0x33: return 6; case 2: case 0x34: return 4;
    case 3: case 0x35: return 10; case 5: case 0x37: return 4;
    case 6: case 0x38: return 4; case 0x39: return 4; case 0x3a: return 12;
    case 0x64: return 8; case 0x65: return 58; case 0x96: return 4; }
  return 2; }
static inline int L55(const uint8_t*p,size_t m){ return 4<=m?4:-1; }
static inline int L72(const uint8_t*p,size_t m){ if(2>m)return -1; uint8_t t=p[1]; size_t i=2; switch(t){
case 0:  break;
case 1:  break;
case 2:  break;
case 3:  break;
case 4:  break;
case 5:  break;
case 6:  break;
case 7:  break;
case 8:  break;
case 9:  break;
default: return 2; } return (int)i; }
static inline int L73(const uint8_t*p,size_t m){ if(2>m)return -1; uint8_t t=p[1]; size_t i=2; switch(t){
case 0: i+=32; break;
case 1: i+=32; break;
case 2: i+=32; break;
case 3: i+=32; break;
case 4: i+=32; break;
case 5:  break;
case 6:  break;
case 7:  break;
case 8:  break;
case 9:  break;
case 10: i+=32; break;
case 11:  break;
case 12:  break;
case 13: {int c=cs1_cstr(p+i,m-i);if(c<0)return -1;i+=c;}{int c=cs1_cstr(p+i,m-i);if(c<0)return -1;i+=c;}i+=4; break;
case 14:  break;
case 15:  break;
case 16:  break;
case 17:  break;
case 18:  break;
case 19:  break;
case 20: {int c=cs1_cstr(p+i,m-i);if(c<0)return -1;i+=c;}{int c=cs1_cstr(p+i,m-i);if(c<0)return -1;i+=c;}i+=10; break;
case 21: {int c=cs1_cstr(p+i,m-i);if(c<0)return -1;i+=c;} break;
case 22:  break;
case 23: i+=5; break;
case 24: i+=3; break;
case 25: {int c=cs1_cstr(p+i,m-i);if(c<0)return -1;i+=c;}{int c=cs1_cstr(p+i,m-i);if(c<0)return -1;i+=c;} break;
case 26:  break;
case 27:  break;
case 28: {int c=cs1_cstr(p+i,m-i);if(c<0)return -1;i+=c;}i+=4; break;
case 29:  break;
case 30:  break;
case 31:  break;
case 32:  break;
case 33: i+=4; break;
case 34:  break;
case 35: i+=2; break;
case 36: i+=2; break;
case 37:  break;
case 38: i+=5;{int c=cs1_cstr(p+i,m-i);if(c<0)return -1;i+=c;} break;
case 39:  break;
case 40: i+=2; break;
case 41: i+=3; break;
default: return 2; } return (int)i; }
static inline int L75(const uint8_t*p,size_t m){ if(2>m)return -1; uint8_t t=p[1]; size_t i=24; switch(t){
case 0:  break;
case 1:  break;
case 2:  break;
case 3:  break;
default: return 24; } return (int)i; }
static inline int L81(const uint8_t*p,size_t m){ if(2>m)return -1; uint8_t t=p[1]; size_t i=2; switch(t){
case 0:  break;
case 1:  break;
case 2:  break;
case 3:  break;
case 4:  break;
default: return 2; } return (int)i; }
static inline int L91(const uint8_t*p,size_t m){ if(2>m)return -1; uint8_t t=p[1]; if(t==0||t==1||t==4)return 6; return 4; }
static inline int L92(const uint8_t*p,size_t m){ if(2>m)return -1; uint8_t t=p[1]; size_t i=4; switch(t){
case 0:  i+=2; break;
case 1:  i+=2; break;
case 2:  break;
case 3:  break;
default: return 4; } return (int)i; }
static inline int L94(const uint8_t*p,size_t m){ if(2>m)return -1; uint8_t t=p[1]; size_t i=2; switch(t){
case 0: i+=8; break;
case 1: i+=2; break;
case 2: i+=6; break;
case 3: i+=6; break;
case 4: i+=2; break;
case 5: i+=6; break;
case 6: i+=10; break;
case 7: i+=2; break;
case 8: i+=2; break;
case 9: i+=2; break;
case 10: i+=5; break;
case 11: i+=2; break;
case 12: i+=4; break;
case 13: i+=4; break;
default: return 2; } return (int)i; }
static inline int L96(const uint8_t*p,size_t m){ if(2>m)return -1; uint8_t t=p[1]; size_t i=18; switch(t){
case 0:  break;
case 1:  break;
case 2:  break;
case 3:  break;
case 4:  break;
case 5:  break;
case 6:  break;
default: return 18; } return (int)i; }
static inline int L110(const uint8_t*p,size_t m){ if(2>m)return -1; return p[1]==5?10:4; }
static inline int L100(const uint8_t*p,size_t m){ return 8<=m?8:-1; }
static inline int L103(const uint8_t*p,size_t m){ if(4>m)return -1; uint8_t t=p[3]; if(t==1||t==2)return 6; if(t==3||t==4)return 5; if(t==5)return 4; if(t==6)return 6; return 3; }
static inline int L105(const uint8_t*p,size_t m){ if(4>m)return -1; uint8_t t=p[3];
  if(t==0)return 8; if(t==1)return 4;
  if(t==2){ if(14>m)return -1; int c=cs1_cstr(p+14,m-14); return c<0?-1:14+c; }
  if(t==3){ if(4>m)return -1; size_t i=4; int c=cs1_cstr(p+i,m-i); if(c<0)return -1; i+=(size_t)c+8; if(i>m)return -1; c=cs1_cstr(p+i,m-i); if(c<0)return -1; return (int)(i+c); }
  return 4; }
// --- handlers ajoutes (extraits de l'asm) ---
static inline int L19(const uint8_t*p,size_t m){ size_t i=3;
  for(int k=0;k<3;k++){ if(i>m)return -1; int c=cs1_cstr(p+i,m-i); if(c<0)return -1; i+=(size_t)c; }
  i+=33;
  for(int k=0;k<2;k++){ if(i>m)return -1; int c=cs1_cstr(p+i,m-i); if(c<0)return -1; i+=(size_t)c; }
  i+=15; return i<=m?(int)i:-1; }
static inline int L39(const uint8_t*p,size_t m){ if(2>m)return -1; uint8_t t=p[1];
  if(t==0x0a){ if(5>m)return -1; int c=cs1_cstr(p+5,m-5); return c<0?-1:5+c; }
  if(t==0x0c){ if(10>m)return -1; int c=cs1_cstr(p+10,m-10); return c<0?-1:10+c+37; }
  if(t==0x15){ if(3>m)return -1; int c=cs1_cstr(p+3,m-3); return c<0?-1:3+c; }
  if(t==0x0b||t==0x0d||t==0x0e||t==0x0f||t==0x10||t==0x11)return 5;
  if(t==0x12)return 7; if(t==0x13||t==0x14)return 21; return 2; }
static inline int L50(const uint8_t*p,size_t m){ if(2>m)return -1; uint8_t t=p[1];
  if(t==0x01){ if(5>m)return -1; size_t i=5; int c=cs1_cstr(p+i,m-i); if(c<0)return -1; i+=(size_t)c; if(i>m)return -1; c=cs1_cstr(p+i,m-i); if(c<0)return -1; return (int)(i+c); }
  if(t==0x02)return 8;
  if(t==0x03){ if(4>m)return -1; size_t i=4; for(int k=0;k<4;k++){ if(i>m)return -1; int c=cs1_cstr(p+i,m-i); if(c<0)return -1; i+=(size_t)c; } return (int)i; }
  if(t==0x04){ if(4>m)return -1; int c=cs1_cstr(p+4,m-4); return c<0?-1:4+c; }
  return 4; }
static inline int L54(const uint8_t*p,size_t m){ if(5>m)return -1; unsigned u=p[3]|((unsigned)p[4]<<8); return (u==0xFE02u||u==0xFE03u)?28:24; }
static inline int L144(const uint8_t*p,size_t m){ if(2>m)return -1; return p[1]==0?4:2; }
static inline int L134(const uint8_t*p,size_t m){ if(2>m)return -1; return (p[1]==0||p[1]==1)?6:2; }
static inline int L154(const uint8_t*p,size_t m){ if(2>m)return -1; uint8_t t=p[1]; if(t==1||t==2)return 10; if(t==3||t==4)return 20; return 2; }
static inline int L111(const uint8_t*p,size_t m){ if(2>m)return -1;
  if(p[1]==0){ int c=cs1_cstr(p+2,m-2); return c<0?-1:2+c; }
  if(4>m)return -1; int c=cs1_cstr(p+4,m-4); return c<0?-1:4+c; }
static inline int L127(const uint8_t*p,size_t m){ if(2>m)return -1; uint8_t t=p[1];
  if(t==0||t==1){ if(6>m)return -1; size_t i=6; int c=cs1_cstr(p+i,m-i); if(c<0)return -1; i+=c;
    if(i>m)return -1; c=cs1_cstr(p+i,m-i); if(c<0)return -1; return (int)(i+c); }
  if(t==0xFE||t==0xFF){ if(4>m)return -1; int c=cs1_cstr(p+4,m-4); return c<0?-1:4+c+4; }
  return 2; }
static inline int L93(const uint8_t*p,size_t m){ if(2>m)return -1; uint8_t t=p[1];
  int c=cs1_cstr(p+2,m-2); if(c<0)return -1; size_t i=2+(size_t)c;
  if(t==0||t==1)return (int)(i+2); if(t>=2&&t<=4)return (int)(i+12);
  if(t==7)return (int)(i+19); if(t==8)return (int)(i+15); return (int)i; }
static inline int L32(const uint8_t*p,size_t m){ if(4>m)return -1; uint8_t t=p[1]; size_t i=4;
  if(t==0){int c=cs1_cstr(p+i,m-i);if(c<0)return -1;i+=c;c=cs1_cstr(p+i,m-i);if(c<0)return -1;return (int)(i+c+1);}
  if(t==1||t==2){int c=cs1_cstr(p+i,m-i);if(c<0)return -1;i+=c;c=cs1_cstr(p+i,m-i);if(c<0)return -1;return (int)(i+c+1);}
  return 4; }
static inline int L136(const uint8_t*p,size_t m){ if(2>m)return -1; return p[1]==0?3:2; }
static inline int L68(const uint8_t*p,size_t m){ if(2>m)return -1; switch(p[1]){case 0:return 20;case 1:return 4;case 2:return 11;case 3:return 23;case 4:return 6;case 5:return 6;default:return 4;} }
static inline int L121(const uint8_t*p,size_t m){ return 18<=m?18:-1; }
static inline int cs1_special(uint8_t op,const uint8_t*p,size_t m){ switch(op){
  case 33:return L33(p,m);
  case 129:return L129(p,m);
  case 145:return L145(p,m);
  case 19:return L19(p,m);
  case 39:return L39(p,m);
  case 50:return L50(p,m);
  case 54:return L54(p,m);
  case 68:return L68(p,m);
  case 32:return L32(p,m);
  case 93:return L93(p,m);
  case 111:return L111(p,m);
  case 127:return L127(p,m);
  case 134:return L134(p,m);
  case 154:return L154(p,m);
  case 144:return L144(p,m);
  case 136:return L136(p,m);
  case 25:return L25(p,m);
  case 60:return L60(p,m);
  case 118:return L118(p,m);
  case 57:return L57(p,m);
  case 112:return L112(p,m);
  case 113:return L113(p,m);
  case 137:return L137(p,m);
  case 138:return L138(p,m);
  case 31:return L31(p,m);
  case 106:return L31(p,m);
  case 95:return L95(p,m);
  case 63:return L63(p,m);
  case 115:return L115(p,m);
  case 101:return L101(p,m);
  case 40:return L40(p,m); case 45:return L45(p,m); case 48:return L48(p,m); case 49:return L49(p,m); case 55:return L55(p,m); case 72:return L72(p,m); case 73:return L73(p,m); case 75:return L75(p,m); case 91:return L91(p,m); case 92:return L92(p,m); case 94:return L94(p,m); case 96:return L96(p,m); case 100:return L100(p,m); case 110:return L110(p,m); case 103:return L103(p,m); case 105:return L105(p,m); case 121:return L121(p,m);
  } return -1; }
static inline int cs1_instr_length(const uint8_t*p,size_t max){
  if(max<1)return -1; uint8_t op=p[0]; if(op>=160)return -1; const OpInfo& oi=OPCODES[op]; size_t i=1;
  for(int k=0;k<48;k++){ OperandType t=oi.operands[k]; if(t==OPD_END)break;
    if(t==OPD_SPECIAL)return cs1_special(op,p,max);
    if(t & OPD_FIX_BASE){ i+=(t&0xFF); continue; }
    switch(t){ case OPD_U8:i+=1;break; case OPD_U16:i+=2;break; case OPD_U32:case OPD_I32:i+=4;break;
      case OPD_CSTR:{int s=cs1_cstr(p+i,max-i);if(s<0)return -1;i+=s;break;}
      case OPD_DIALOG:{int s=cs1_dialog(p+i,max-i);if(s<0)return -1;i+=s;break;}
      case OPD_EXPR:{int s=cs1_expr(p+i,max-i);if(s<0)return -1;i+=s;break;}
      case OPD_SWITCH:{if(i>=max)return -1;uint8_t n=p[i];i+=1+(size_t)n*6+4;break;}
      default:return -1; } if(i>max)return -1; }
  return (int)i; }

// --- decoupage OP / DATA d'une fonction (conservation roundtrip) ---
// Les blocs atteints uniquement par saut (tables op06, blocs pointes) suivent un
// yield op0 et debutent par un octet non-opcode (>159). On les conserve bruts :
// non decodes, mais preserves pour un roundtrip byte-exact.
enum { CS1_SEG_OP = 0, CS1_SEG_DATA = 1 };
struct Cs1Seg { int kind; uint32_t start; uint32_t len; };

static inline bool cs1_reaches_end(const uint8_t* buf, uint32_t st, uint32_t e){
    uint32_t p = st;
    while (p < e){
        int L = cs1_instr_length(buf + p, e - p);
        if (L <= 0 || (uint32_t)L > e - p) return false;
        p += (uint32_t)L;
    }
    return p == e;
}

// Remplit segs[] (max maxsegs). Retourne le nombre de segments, ou -1 si debordement.
// Les segments couvrent EXACTEMENT [s,e).
static inline int cs1_parse_function(const uint8_t* buf, uint32_t s, uint32_t e,
                                     Cs1Seg* segs, int maxsegs){
    int n = 0;
    uint32_t p = s;
    while (p < e){
        int L = cs1_instr_length(buf + p, e - p);
        if (L > 0 && (uint32_t)L <= e - p){
            if (n >= maxsegs) return -1;
            segs[n].kind = CS1_SEG_OP; segs[n].start = p; segs[n].len = (uint32_t)L;
            n++; p += (uint32_t)L; continue;
        }
        uint32_t st = p + 1;
        while (st < e && !cs1_reaches_end(buf, st, e)) st++;
        if (n >= maxsegs) return -1;
        segs[n].kind = CS1_SEG_DATA; segs[n].start = p; segs[n].len = st - p;
        n++; p = st;
    }
    return n;
}


// ================= TABLES (portage CS1Decompiler) =================
// Reader avec drapeau d'echec (equivalent des _TableThrow / bornes Python).
struct Cs1Rd { const uint8_t* b; long p; long n; bool fail; };
static inline void   cr_adv(Cs1Rd*r,long k){ if(r->fail)return; if(k<0||r->p+k>r->n){r->fail=true;return;} r->p+=k; }
static inline long   cr_rstr(Cs1Rd*r){ if(r->fail)return 0; long st=r->p; while(r->p<r->n&&r->b[r->p]!=0)r->p++; if(r->p>=r->n){r->fail=true;return 0;} r->p++; return r->p-st; }
static inline int32_t cr_i32(Cs1Rd*r){ if(r->fail||r->p<0||r->p+4>r->n){r->fail=true;return 0;} const uint8_t*q=r->b+r->p; return (int32_t)(q[0]|(q[1]<<8)|(q[2]<<16)|((uint32_t)q[3]<<24)); } // peek
static inline int    cr_u16(Cs1Rd*r){ if(r->fail||r->p+2>r->n){r->fail=true;return 0;} return r->b[r->p]|(r->b[r->p+1]<<8); } // peek
static inline int    cr_i16(Cs1Rd*r){ int v=cr_u16(r); return v>=0x8000?v-0x10000:v; }
static inline uint8_t cr_b(Cs1Rd*r){ if(r->fail||r->p<0||r->p>=r->n){r->fail=true;return 0;} return r->b[r->p]; } // peek

// Chaque parseur avance r->p ; renvoie via r->fail. goal = fin de fonction.
static inline void T_CreateMonsters(Cs1Rd*r,long goal){ long initial=r->p;
  if(goal<r->p+0x20){r->fail=true;return;} if(cr_i32(r)==-1){cr_adv(r,0x1C);return;}
  long ms=cr_rstr(r); cr_adv(r,0x10-ms); cr_adv(r,4); for(int i=0;i<6;i++)cr_adv(r,2);
  long cnt=0;
  for(;;){ if(goal<initial+0x20+cnt*0x90){r->fail=true;return;} cr_adv(r,4);
    for(int i=0;i<8;i++){ long n=cr_rstr(r); cr_adv(r,0x10-n); }
    for(int i=0;i<8;i++)cr_adv(r,1);
    if(r->fail)return; if(cr_b(r)==0)cr_adv(r,8); else{ long n=cr_rstr(r); cr_adv(r,12-n); }
    if(r->fail)return; int32_t first=cr_i32(r); cnt++;
    if(!(first!=-1&&r->p!=goal-4))break; }
  if(r->p==goal-4){ if(cr_i32(r)!=1)r->fail=true; return; }
  cr_adv(r,0x1C);
}
static inline void T_Effects(Cs1Rd*r,long goal){ (void)goal;
  for(;;){ if(r->fail||r->p>=r->n){r->fail=true;return;} if(cr_b(r)==0x01)return;
    cr_adv(r,2);cr_adv(r,2);cr_adv(r,4); long n=cr_rstr(r); cr_adv(r,0x20-n); } }
static inline void T_ActionTable(Cs1Rd*r,long goal){ (void)goal; int cnt=cr_b(r); cr_adv(r,1);
  for(int i=0;i<cnt&&!r->fail;i++){ cr_adv(r,2); cr_adv(r,10); for(int j=0;j<7;j++)cr_adv(r,2);
    long n; n=cr_rstr(r);cr_adv(r,0x10-n); n=cr_rstr(r);cr_adv(r,0x20-n); n=cr_rstr(r);cr_adv(r,0x30-n); } }
static inline void T_AlgoTable(Cs1Rd*r,long goal){ (void)goal; int cnt=cr_b(r); cr_adv(r,1);
  for(int i=0;i<cnt&&!r->fail;i++){ int sh=cr_i16(r); cr_adv(r,2); cr_adv(r,0x1E); if(sh==-1)cr_adv(r,8); } }
static inline void T_WeaponAtt(Cs1Rd*r,long goal){ (void)goal; cr_adv(r,4); }
static inline void T_BreakTable(Cs1Rd*r,long goal){ (void)goal; int c=0;
  for(;;){ int sh=cr_i16(r); cr_adv(r,2); if(r->fail)return; if(sh==0)break; cr_adv(r,2); if(++c>=0x40)break; } cr_adv(r,2); }
static inline void T_SummonTable(Cs1Rd*r,long goal){ (void)goal; int cnt=cr_b(r); cr_adv(r,1);
  for(int i=0;i<cnt&&!r->fail;i++){ int sh=cr_u16(r); cr_adv(r,2); if(sh==0xFFFF)break; cr_adv(r,1);cr_adv(r,1); long n=cr_rstr(r); cr_adv(r,0x20-n); } }
static inline void T_ReactionTable(Cs1Rd*r,long goal){ (void)goal; int cnt=cr_u16(r); cr_adv(r,2);
  for(int i=0;i<cnt&&!r->fail;i++){ for(int j=0;j<6;j++)cr_adv(r,2); } }
static inline void T_PartTable(Cs1Rd*r,long goal){ (void)goal; int cnt=cr_b(r); cr_adv(r,1);
  for(int i=0;i<cnt&&!r->fail;i++){ cr_adv(r,4); long n; n=cr_rstr(r);cr_adv(r,0x20-n); n=cr_rstr(r);cr_adv(r,0x20-n); } }
static inline void T_AnimeClip(Cs1Rd*r,long goal){ (void)goal;
  while(!r->fail&&cr_i32(r)!=0){ cr_adv(r,4); long n; n=cr_rstr(r);cr_adv(r,0x20-n); n=cr_rstr(r);cr_adv(r,0x20-n); } cr_adv(r,4); cr_adv(r,2); }
static inline void T_FieldMonster(Cs1Rd*r,long goal){ (void)goal; cr_adv(r,4);cr_adv(r,2);cr_adv(r,2); while(!r->fail&&cr_i32(r)!=1)cr_adv(r,4); }
static inline void T_FieldFollow(Cs1Rd*r,long goal){ (void)goal; for(int i=0;i<5;i++)cr_adv(r,4); }
static inline void T_FC_auto(Cs1Rd*r,long goal){ (void)goal; cr_rstr(r); }
static inline void T_Book99(Cs1Rd*r,long goal){ (void)goal; cr_adv(r,2);cr_adv(r,2); }
static inline void T_BookX(Cs1Rd*r,long goal){ (void)goal; int ctrl=cr_i16(r); cr_adv(r,2);
  if(ctrl>0){ cr_adv(r,2); long n=cr_rstr(r); cr_adv(r,0x10-n); for(int i=0;i<10;i++)cr_adv(r,2); cr_rstr(r); }
  else { if(!r->fail&&cr_b(r)!=1)cr_rstr(r); } }
static inline void T_AddCollision(Cs1Rd*r,long goal){ (void)goal; int cnt=cr_b(r); cr_adv(r,1);
  for(int i=0;i<cnt&&!r->fail;i++){ cr_adv(r,4); for(int j=0;j<5;j++)cr_adv(r,4); } }

typedef void(*Cs1TabFn)(Cs1Rd*,long);
static inline Cs1TabFn cs1_table_parser(int t){ switch(t){
  case 1:return T_CreateMonsters; case 2:return T_Effects; case 3:return T_ActionTable; case 4:return T_AlgoTable;
  case 5:return T_WeaponAtt; case 6:return T_BreakTable; case 7:return T_SummonTable; case 8:return T_ReactionTable;
  case 9:return T_PartTable; case 10:return T_AnimeClip; case 11:return T_FieldMonster; case 12:return T_FieldFollow;
  case 13:return T_FC_auto; case 14:return T_Book99; case 15:return T_BookX; case 16:return T_AddCollision; default:return 0; } }

// nom -> liste de types candidats (Builder::guess_type_by_name). out doit avoir >=3 cases.
static inline int cs1_guess_types(const char* nm, int* out){
  if(!nm)nm="";
  struct { const char* n; int t; } E[]={{"ActionTable",3},{"AlgoTable",4},{"WeaponAttTable",5},{"BreakTable",6},
    {"SummonTable",7},{"ReactionTable",8},{"PartTable",9},{"AnimeClipTable",10},{"FieldMonsterData",11},
    {"FieldFollowData",12},{"AddCollision",16},{"ConditionTable",17}};
  for(unsigned i=0;i<sizeof(E)/sizeof(E[0]);i++) if(strcmp(nm,E[i].n)==0){ out[0]=E[i].t; return 1; }
  if(strncmp(nm,"FC_auto",7)==0){ out[0]=13; return 1; }
  if(strncmp(nm,"BookData",8)==0){ const char* u=strchr(nm,'_'); int b99=(u&&strcmp(u+1,"99")==0); out[0]=b99?14:15; return 1; }
  if(strncmp(nm,"StyleName",9)==0){ out[0]=18; return 1; }
  if(nm[0]=='_'){ out[0]=0; out[1]=2; return 2; }
  out[0]=0; out[1]=1; out[2]=2; return 3;
}

static inline bool cs1_try_code(const uint8_t*b,long s,long e){ long p=s;
  while(p<e){ int L=cs1_instr_length(b+p,e-p); if(L<=0||(long)L>e-p)return false; p+=L; } return p==e; }
static inline bool cs1_try_table(const uint8_t*b,long s,long e,int t){ Cs1TabFn f=cs1_table_parser(t); if(!f)return false;
  Cs1Rd r={b,s,e,false}; f(&r,e); if(r.fail)return false; long p=r.p;
  int L=cs1_instr_length(b+p,e-p); if(L<=0||(long)L>e-p)return false; p+=L;
  while(p<e){ if(b[p]!=0)return false; p++; } return p==e; }

// Renvoie le type (0=code,1..18=table) si un candidat parse proprement jusqu'a e ; sinon -1
// (l'appelant utilise alors cs1_parse_function pour code+chunks).
static inline int cs1_classify_function(const uint8_t*b,const char*name,long s,long e){
  int cand[3]; int nc=cs1_guess_types(name,cand);
  for(int i=0;i<nc;i++){ int t=cand[i];
    if(t==0){ if(cs1_try_code(b,s,e))return 0; }
    else if(cs1_table_parser(t)){ if(cs1_try_table(b,s,e,t))return t; } }
  if(cs1_try_code(b,s,e))return 0;   // fallback code (comme Python)
  return -1;
}

} // namespace cs1