<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\ED8Editor.Core\ED8Editor.Core.csproj" />
    <PackageReference Include="Vortice.Direct3D11" Version="2.4.2" />
    <PackageReference Include="Vortice.D3DCompiler" Version="2.4.2" />
  </ItemGroup>
</Project>
